### ISSUE TITLE
Installing pgsync (Errno::ENOTSUP) Operation not supported - copy_file_range

### ISSUE THREAD

**Issue by equest111** [ankane/pgsync#103]
I am trying to install latest version of pgsync for the first time and getting the error: 
  ERROR:  While executing gem ... (Errno::ENOTSUP)
      Operation not supported - copy_file_range

https://bugzilla.redhat.com/show_bug.cgi?id=1783554 indicates this is a kernel issue and resolved in kernel-3.10.0-1149.el7 and kernel-3.10.0-1152.el7 but I cannot upgrade to these versions.

Machine versions:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
gem -v 3.1.2
Red Hat Enterprise Linux Server release 7.8 (Maipo)
3.10.0-1127.18.2.el7.x86_64

Please let me know if you have any thoughts on how to work around this to install pgsync.

**Comment by ankane** [comment]
Hey @equest111, I haven't seen that error before, but it doesn't seem like an issue with pgsync.

**Comment by equest111** [comment]
Using ruby v2.4.0 resolves the error as copy file range introduced in ruby v2.5.0.

Laurel

**Comment by ankane** [comment]
Glad you found a solution, and thanks for sharing.
