### ISSUE TITLE
Define the destination ("to") schema. 

### ISSUE THREAD

**Issue by thewandererbg** [ankane/pgsync#104]
Hi,

Could you help me with these 2 questions?

1) Is it possible to define the "to" schema? In other words, is it possible to sync from db1 schema1 to db2 schema2? Now I can only find out the way to sync from db1:schema1 to db2:schema1?

2) Is it possible that the "to" table name to be different from the "from" table name using a predefined format such as: shema_tablename (public_products for example)?

Thanks,

**Comment by ankane** [comment]
Hey @thewandererbg, pgsync doesn't support syncing to a different schema or table, but you could probably fork and make it work.

**Comment by ankane** [comment]
Cleaning up issues
