### ISSUE TITLE
libpq is too old. Upgrade it and run `gem install pg`

### ISSUE THREAD

**Issue by equest111** [ankane/pgsync#105]
When running 'pgsync' getting the error **libpq is too old. Upgrade it and run `gem install pg`** .

ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
gem version 3.0.8
Package postgresql-libs-9.2.24-4.el7_8.x86_64 already installed and latest version
Red Hat Enterprise Linux Server 7.8 (Maipo)"
Kernel 3.10.0-1127.18.2.el7.x86_64

Due to linux rhel 7.8 kernel issue with copy_file_range, have to use ruby version less than 2.5.0 where copy_file_range was introduced.

Any assistance is appreciated. Getting pgsync up and running has been an exercise.

**Comment by ankane** [comment]
Hey @equest111, `postgresql-libs-9.2` isn't supported. Install a more recent version and reinstall the `pg` gem.

```sh
gem install pg -- --with-pg-config=/path/to/pg_config
```

**Comment by equest111** [comment]
PG11.6 is already installed and running.
package postgresql11-libs-11.6-2PGDG.rhel7.x86_64 is already installed
$ /usr/pgsql-11/lib
   libpq.so.5
   libpq.so.5.11
   
$ gem install pg -- --with-pg-config=/usr/pgsql-11/bin/pg_config --> installs pg-1.2.3 successfully.

$pgsync
libpq is too old. Upgrade it and run `gem install pg`

**Comment by ankane** [comment]
The error indicates the `pg` gem that `pgsync` is picking up was compiled against `postgresql-libs-9.2`. See this discussion for a previous instance and resolution: https://github.com/ankane/pgsync/issues/88#issuecomment-627979815

**Comment by equest111** [comment]
Thanks.
1) I did 'rm -rf ~/.rvm/gems/ruby-2.4.0/gems/pg-1.2.3'
2) I ran 'gem install pg -- --with-pg-config=/usr/pgsql-11/bin/pg_config' successfully
3) $ pgsync --list 
    $ libpq is too old. Upgrade it and run `gem install pg`

**Comment by ankane** [comment]
Unfortunately, I'm not sure there's much more I can do to help without setting up a similar environment, which I don't have the bandwidth for. If you figure out how to make it work, please update so others can benefit.

**Comment by ankane** [comment]
Cleaning up issues
