### ISSUE TITLE
extra key/value separator "=" in URI query parameter: "fallback_application_name"

### ISSUE THREAD

**Issue by buidinhduong** [ankane/pgsync#106]
I met this issue,  even i don't use any fallback_application_name parameter.
, please help

**Comment by ankane** [comment]
Hey @buidinhduong, unfortunately, I'm not sure how to reproduce. pgsync doesn't use that parameter, so it's likely something with one of your database URLs or environment variables.

**Comment by ankane** [comment]
Cleaning up issues
