### ISSUE TITLE
Question about sensitive login information

### ISSUE THREAD

**Issue by pcthomatos** [ankane/pgsync#107]
In the comments it says

>   we recommend a command which outputs a database URL

Can you provide an example?

**Comment by ankane** [comment]
Hey @pcthomatos, it could be as simple as:

```sh
echo $DATABASE_URL
```

if your credentials are stored in an environment variable, or if you use a platform like Dokku, something like:

```sh
dokku config:get DATABASE_URL
```

**Comment by pcthomatos** [comment]
Hi Thank you for the prompt reply..

I'm trying to figure out how to pull the **from** and **to** values as environment variables in the yml. Either the full value as an environment variable or the just the credentials.

**Comment by ankane** [comment]
Use the command above:

```yml
from: $(echo $FROM_DATABASE_URL)
to: $(echo $TO_DATABASE_URL)
```

**Comment by pcthomatos** [comment]
Thank you that's what I was looking for!
