### ISSUE TITLE
Exclude generated column

### ISSUE THREAD

**Issue by stem** [ankane/pgsync#108]
Hello,

I'm trying to use this gem to sync some tables from a pg instance to another (prod -> staging) but I can't manage to make it skip a generated column on a table.

I've got this error : 
```
✖ spree_products WHERE deleted_at IS NULL (cannot insert into column "searchable")
```

where `searchable` is defined like this : 
```
   Column   |   Type   | Collation | Nullable |                                      Default                                       
 searchable | tsvector |           |          | generated always as (to_tsvector('unaccent_french'::regconfig, name::text)) stored
```

I've tried to configure it with `spree_products.searchable: null` and `spree_products.searchable: untouched ` but neither seems to ignore the column :(
I've even tried `--disable-user-triggers products` without luck 😞 
Do you have any Idea of how I can manage this generated column ?

**Comment by ankane** [comment]
Hey @stem, thanks for reporting! Fixed on master. You can try it out with the instructions here: https://github.com/ankane/pgsync#upgrading

**Comment by stem** [comment]
Hey @ankane, thank you for this quick reply!

Unfortunately, this fix doesn't work as expected. It still fails with the following message : 
```
✖ spree_products WHERE deleted_at IS NULL (cannot insert into column "searchable")
```

I've managed to follow the process flow and find that the `searchable` field is still created in the temporary table `pgsync_442504969 ` with a `null` value.
It is indeed removed from the `ON CONFLICT` part but seems to be found in the `INSERT INTO "public"."spree_products" (SELECT * FROM "pgsync_442504969")` part.

**Comment by ankane** [comment]
Make sure you've installed and are running the version from master.

**Comment by stem** [comment]
I'm positive I'm using master but the bug remains. I've found a fix and making a small PR.
