### ISSUE TITLE
With Truncate, just delete rows in where clause instead of all existing rows

### ISSUE THREAD

**Issue by aebrahimian** [ankane/pgsync#110]
Hi,
I think when --truncate is used it would be better (or have an option) to just delete rows in where clause in destination. Consider i have a very large table and i want to just sync today data. It would be great if it first delete just today data (e.g with where clause on date) on destination, and then copy today data from source to destination.

**Comment by ankane** [comment]
Hey @aebrahimian, unless I'm misunderstanding, this is how it works if you specify a SQL clause without any options.

```sh
pgsync table "where created_at > NOW() - INTERVAL '1 day'"
```

**Comment by aebrahimian** [comment]
Yes, but it doesn't delete existing rows for today in destination. I think it would be great if there was an option that you can tell pgsync to also delete existing rows in dest with where clause

**Comment by aebrahimian** [comment]
> Hey @aebrahimian, unless I'm misunderstanding, this is how it works if you specify a SQL clause without any options.
> 
> ```shell
> pgsync table "where created_at > NOW() - INTERVAL '1 day'"
> ```
> 
> Edit: On 2nd thought, it seems like the current method won't sync deleted rows. Happy to add a `--delete` option for this if you'd like to submit a PR.

By sync deleted rows, you mean to delete rows with where clause in the destination? If it is so, then that what I asked for
I'm not a ruby guy to submit a PR, but i would appreciate it if you add this feature in the future. 
thanks for your great tool and support

**Comment by ankane** [comment]
Yeah, my bad, I missed what you were suggesting when I first read it. I've added it to the ideas list in case someone wants to add it.

**Comment by aebrahimian** [comment]
> Yeah, my bad, I missed what you were suggesting when I first read it. I've added it to the ideas list in case someone wants to add it.

Great, thanks

**Comment by ankane** [comment]
Cleaning up issues
