### ISSUE TITLE
Sync schema not sync views

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ankane/pgsync#115]
I test that pgsync not sync views (--schema-only), only tables.
I use the following:
pgsync schema.* --schema-only --schemas schema --from postgres://user:@localhost:5432/dbfrom --to postgres://user:@localhost:5432/dbto.

What am I doing wrong?

**Comment by xiaohui-zhangxh** [comment]
I got the same issue, table view can't be synced.

**Comment by ankane** [comment]
Hey @cesarjorgemartinez and @xiaohui-zhangxh, pgsync is only designed to sync tables, so you'll probably want to look at another solution for syncing views (you might also be able to fork and add this functionality).
