### ISSUE TITLE
How to achieve parallelism?

### ISSUE THREAD

**Issue by ignaski** [ankane/pgsync#117]
Hi, so far pgsync looks very promising for my use case, but I can not find the way to achieve parallelism. Data is transferred on a table-by-table basis. Am I missing any specific options?

**Comment by ignaski** [comment]
I think I found the answer, --jobs option :)
However, it seems that I am running into performance issue with indexed tables, i.e. index is being updated during copy operation. It would be nice to see a feature that allows to drop / re-create indexes in future versions of pgsync!

**Comment by ankane** [comment]
Hey @ignaski, the `--jobs` option should work, which by default is set to the number of cores on your machine.

Dropping and recreating indexes is an interesting idea, but don't think it's a common enough need to support (and prefer not to mess with the schema when possible).
