### ISSUE TITLE
schema-only sync ignoring ssl cert path

### ISSUE THREAD

**Issue by terkin** [ankane/pgsync#119]
So my config looks like

`
to: postgres://XXX:5432/XXX?sslmode=verify-full&sslrootcert=BaltimoreCyberTrustRoot.crt.pem
`

and tables sync works fine, but when I am trying to run
pgsync table_xxx --schema-only --debug
I got: 

`pg_restore: error: connection to database "XXX" failed: root certificate file "/Users/XXX/.postgresql/root.crt" does not exist
Either provide the file or change sslmode to disable server certificate verification.`

so it seams like its ignoring some db uri params during this sync mode

**Comment by ankane** [comment]
Hey @terkin, thanks for reporting! This turned out to be a security vulnerability and is fixed in 0.6.7. See #121 for more info.
