### ISSUE TITLE
Remove Heroku Gem Dependency

### ISSUE THREAD

**Issue by Tybot204** [ankane/pgsync#12]
On April 17th the Legacy API for Heroku will be sunset. I would love to see this gem continue supporting Heroku after that date. It looks like there is a new gem implemented to cover interaction with Heroku without having Heroku Toolbelt installed. I haven't take a super long look at it, but at a glance it looks like it can replace the Heroku gem here.

Link to gem: https://github.com/heroku/platform-api
API reference: https://devcenter.heroku.com/articles/platform-api-reference

**Comment by Tybot204** [comment]
It appears this might only be used in the `.pgsync` generator and could be a simple fix. I'll take a look into getting a PR up.

**Comment by ankane** [comment]
Hey @Tybot204, this project doesn't use the Heroku API directly, just the toolbelt, which should still work.

**Comment by Tybot204** [comment]
@ankane Hmm maybe I'm missing something then.

When I ran `pgsync --setup`, the autogenerated `.pgsync.yml` config file has a Heroku command in it that doesn't seem to be using the toolbelt, but does work when I install the Heroku gem inside my project.

Error I'm getting without Heroku gem:
```
/.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:408:in `block in replace_bin_path': can't find executable heroku (Gem::Exception)
    from /.rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/rubygems_integration.rb:425:in `block in replace_bin_path'
    from /.rvm/gems/ruby-2.3.3/bin/heroku:22:in `<main>'
    from /.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
    from /.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Tybot204** [comment]
@ankane I figured it out. I had previously installed the Heroku gem a long time ago on my machine. Since it was still installed, that error was being thrown. I completely removed it from my machine and it works fine using just the toolbelt now. Closing the issue!
