### ISSUE TITLE
Cannot sync from Heroku to local?

### ISSUE THREAD

**Issue by pil0u** [ankane/pgsync#120]
Hello Andrew, I fail to make the gem work properly with Heroku and Rails. Here are the steps I did.

1. `gem install pgsync` on my PopOS 20.04 :heavy_check_mark: 
2. In my Rails app, I ran `pgsync --init` which correctly generated the `.pgsync.yml` file :heavy_check_mark: 
3. I edit the file to match my Heroku Database, the file looks like this:

``` yml
from: $(heroku config:get DATABASE_URL -a my-heroku-app)?sslmode=require
to: postgres://localhost:5432/web_development
exclude:
  - ar_internal_metadata
  - schema_migrations
```

The command `heroku config:get DATABASE_URL -a my-heroku-app` on its own properly returns the database URI, which looks like `postgres://someuser:a0b1c2d3e4f56789@ec2-54-228-174-49.eu-west-1.compute.amazonaws.com:5432/somedatabase`, so fine to me.

In my Heroku database, there is a `users` table with 2 users in it. I try:
``` zsh
pgsync users --debug
```
which returns this error:

``` zsh
Traceback (most recent call last):
	11: from /home/pierreloic/.rbenv/versions/2.7.3/bin/pgsync:23:in `<main>'
	10: from /home/pierreloic/.rbenv/versions/2.7.3/bin/pgsync:23:in `load'
	 9: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/exe/pgsync:7:in `<top (required)>'
	 8: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/client.rb:34:in `start'
	 7: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/client.rb:25:in `perform'
	 6: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/sync.rb:33:in `perform'
	 5: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:18:in `local?'
	 4: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:22:in `host'
	 3: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:169:in `conninfo'
	 2: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:96:in `conn'
	 1: from /home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:96:in `new'
/home/pierreloic/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/pgsync-0.6.6/lib/pgsync/data_source.rb:96:in `initialize': fe_sendauth: no password supplied (PG::ConnectionBad)
```
I don't really understand the error because the URI is supposed to embed the database password, isn't it? I might be missing something probably obvious, so any hunch is welcome.

Thank you!

**Comment by ankane** [comment]
Hey @pil0u, from the backtrace, it looks like an error with the destination, which doesn't have a password in the config above.

**Comment by pil0u** [comment]
Thank you for your answer, it was indeed related to the destination (I'm not sure what in the backtrace points to that direction).

Working with Rails, I have never had to dive into my local PostgreSQL configuration. I actually learned some things about [PostgreSQL Authentication Methods](https://www.postgresql.org/docs/12/auth-methods.html).

Indeed, this line was problematic:
``` yml
to: postgres://localhost:5432/web_development
```
and needed to be changed to something like:
``` yml
to: postgres://username:password@localhost:5432/web_development
```
where `username` and `password` are my local PostgreSQL credentials :heavy_check_mark: 

On a side note, could you confirm that `?sslmode=require` is the best we can do with Heroku?

**Comment by ankane** [comment]
That's my understanding if you don't have a [Private or Shield plan](https://devcenter.heroku.com/articles/heroku-postgres-via-mtls).

**Comment by richarddavenport** [comment]
@ankane I'm running my local environment without a password, not sure what to do. I'm also getting `fe_sendauth: no password supplied (PG::ConnectionBad)`.
