### ISSUE TITLE
Occasionally tables are truncated even with `--disable-integrity` flag

### ISSUE THREAD

**Issue by vicramon** [ankane/pgsync#125]
Often I want to sync just one table and ignore foreign key constraints. I'm using `--disable-integrity` for this. 

But sometimes when I do this many related tables get truncated, then I have to re-sync all those tables. 

Is this the expected behavior and I'm missing something?

For example:

```
$ pgsync programmatic_publishers --disable-integrity
....
✔ programmatic_publishers - 0.2s
NOTICE:  truncate cascades to table "programmatic_publisher_creatives"
NOTICE:  truncate cascades to table "programmatic_won_responses"
NOTICE:  truncate cascades to table "publisher_ssps"
NOTICE:  truncate cascades to table "bid_spends"
NOTICE:  truncate cascades to table "bid_spends_default"
NOTICE:  truncate cascades to table "plan_publishers"
NOTICE:  truncate cascades to table "budgets"
NOTICE:  truncate cascades to table "bid_locations"
NOTICE:  truncate cascades to table "bid_locations_default"
```

**Comment by ankane** [comment]
Hey @vicramon, if you fork and remove the `CASCADE` from [this line](https://github.com/ankane/pgsync/blob/3c30319e14936e36a330c2407fe8926f23ae1d23/lib/pgsync/data_source.rb#L68), does it work as expected? If so, we can remove the cascade when `--disable-integrity` is specified.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by richarddavenport** [comment]
@ankane I'm not a ruby dev, and I did try to fork and remove that line, but unfortunately I couldn't test it locally. I would love to try it locally. I ran `bundle install` but not sure how to try out these new changes. Can you help me out?

**Comment by ankane** [comment]
Hey @richarddavenport, if you run:

```sh
bundle exec rake install
```

it'll install the local changes and then you can run `pgsync` as normal.

**Comment by richarddavenport** [comment]
Following up... @ankane removing `CASCADE` does fix the overall issue. I can try and submit a PR, but I've never written a line of ruby code... so the chances of it being correct are slim! HA! I can get one started and maybe you could help?
