### ISSUE TITLE
Schema-only syncs fail with a secondary schema

### ISSUE THREAD

**Issue by chrismanderson** [ankane/pgsync#126]
Might be a bug, might be something I'm doing wrong - I have a Heroku database with two schemas ('public' and 'salesforce' - using the Heroku Connect Salesforce product) used with a Rails app.

Because Heroku manages the `salesforce` schema, it's not present in Rails migrations or anything like that. I was hoping to use `pgsync` to pull that schema into my `structure.sql` file.

However, whenever I try to do so, pgsync fails to create any salesforce tables saying the schema does not exist.

Running `pgsync --schema-only --all-schemas` outputs a huge output, with the main kicker being

```
pg_restore: error: could not execute query: ERROR:  schema "salesforce" does not exist
```

(`pgsync --schemas salesforce --schema-first`) outputs the same.

when I would imagine pg_restore should be creating the schema. 

Doing `pgsync --all-schemas` outputs

```
Missing tables: salesforce._hcmeta, salesforce._sf_event_log, salesforce._trigger_log....
```

Am I assuming `pgsync` can create the schema locally when in fact in cannot? Or am I missing a command or flag perhaps? Thanks!

**Comment by ankane** [comment]
Hey @chrismanderson, thanks for reporting! It looks like `pg_dump` doesn't create schemas when the `-t` option is specified, so I've updated pgsync to do it.

**Comment by chrismanderson** [comment]
Awesome, much appreciated!

**Comment by sebaxtian** [comment]
Hi, I have this error related to --schema-only option:

pgsync --schema-only --exclude ""
Usage: pgsync [OPTIONS]
Try 'pgsync --help' for help.

Error: no such option: --schema-only

Please, could you help me?
