### ISSUE TITLE
How can i pass source db via command line? 

### ISSUE THREAD

**Issue by underscore-ex** [ankane/pgsync#127]
I have to write a script which should allow users to do sycn with different db. I am writing a shell script whcih will ask which db needs to be synced and then will proceed with its details. That means that my `.pgsync.yml` file needs dynamic `from:` value. How can i pass that. I couldn't find any documentation or help on it.

**Comment by ankane** [comment]
Hey @underscore-ex, the generated `.pgsync.yml` file should have an example of how to use a script.

```yml
from: $(some_command)?sslmode=require
```

However, it won't work with interactive scripts.

**Comment by valeriy-trus-gismart** [comment]
Hello, @ankane. I try to use pgsync like 'pgsync --to-safe --from postgres://user:pass@host:port/db --to postgres://user:pass@host:port/db --all-schemas'. But it doesn't work. There is message "unknown option `--from postgres://user:pass@host:5432/db'" in log file. What  do I do wrong?
