### ISSUE TITLE
Defer constraints v2 flag locks TO DB

### ISSUE THREAD

**Issue by HarshaLaxman** [ankane/pgsync#128]
**What**

All tables are locked in the TO DB when using defer-constraints due to “ALTER TABLE ALTER CONSTRAINT DEFERRABLE” 
https://github.com/ankane/pgsync/blob/3c30319e14936e36a330c2407fe8926f23ae1d23/lib/pgsync/table_sync.rb#L277

**Why**:

https://www.postgresql.org/docs/13/explicit-locking.html  “Only an ACCESS EXCLUSIVE lock blocks a SELECT (without FOR UPDATE/SHARE) statement.”

 https://www.postgresql.org/docs/13/sql-altertable.html  “An ACCESS EXCLUSIVE lock is acquired unless explicitly noted. When multiple subcommands are given, the lock acquired will be the strictest one required by any subcommand”

**Proposals** (choose one):

1. Manually set the isolation level for the txn: `BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED’. Unsure what downstream effects this would have - other SQL commands in pgsync may change the isolation level and rely on the change?

2. Add a flag `—set-all-deferrable` ? (naming is hard) which defaults to True -> pgsync behaves as it does now. If set to False, pgsync should only run `SET CONSTRAINTS ALL DEFERRED` and the user is responsible for running the `ALTER TABLE ALTER CONSTRAINT DEFERRABLE` commands outside the pgsync txn.

**Comment by HarshaLaxman** [comment]
Created PR for proposal 2. Changed flag name to `--skip-alter-constraints` in order to keep with the pattern of flags defaulting to false.

**Comment by ankane** [comment]
Hey @HarshaLaxman, thanks for the PR.

For 1, it looks like `READ COMMITTED` is the default isolation level. https://www.postgresql.org/docs/current/transaction-iso.html

For 2, only non-deferrable constraints should be updated, so I'm not sure another option is needed.

**Comment by HarshaLaxman** [comment]
Hey @ankane thanks for the quick response! 

For 2, I think the solution to avoid locking without the `--skip-alter-constraints` flag would be to set all constraints as deferrable before running pgsync. With the flag, one would only need to set the foreign keys that are known to be affected during sync as deferrable.

**Comment by ankane** [comment]
I think it may be better to update the existing code to only alter constraints that are affected by the sync (rather than a new option).

**Comment by ankane** [comment]
Cleaning up stale issues. See the previous comment for my latest thoughts.
