### ISSUE TITLE
Special characters removed from connection strings

### ISSUE THREAD

**Issue by HarshaLaxman** [ankane/pgsync#130]
https://github.com/ankane/pgsync/blob/90cd26e4363a337111a7956a2f67eb8d149072d8/lib/pgsync/sync.rb#L146 

Passwords (and maybe usernames?) can contain special characters and work with psql, which can make this error msg confusing https://github.com/ankane/pgsync/blob/45246c79ce37bbd6dd3b5035f39e22cf6250fe4a/lib/pgsync/data_source.rb#L115

I don’t know the reason `resolve_source` is implemented this way, or even what it is doing (what is `m`?), but maybe a workaround would be to url encode before doing the replacement? If not possible, maybe a note in the README telling users to URL encode their cxn strings?

**Comment by ankane** [comment]
Hey @HarshaLaxman, special characters need to be URL-encoded, just like with psql.
