### ISSUE TITLE
error 'pg_restore not found' when running via docker

### ISSUE THREAD

**Issue by tlwt** [ankane/pgsync#132]
When running `pg_sync`with  `--schema-first` using `ankane/pgsync` from the docker hub registry I get a `pg_restore not found` error.

Adding `postgresql` to the `RUN apk add` seems to fix it (though there might be more efficient approaches).

**Comment by ankane** [comment]
Hey @tlwt, thanks for reporting. Just pushed a new image to the `latest` tag.

**Comment by aliammaar** [comment]
> Hey @tlwt, thanks for reporting. Just pushed a new image to the `latest` tag.

Hi @ankane, Thanks much for the great solution! 
I am having this error on latest version.

```
bundle info pgsync
  * pgsync (0.7.0)
	Summary: Sync Postgres data between databases
	Homepage: https://github.com/ankane/pgsync
	Path: /path/shared/bundle/ruby/2.5.0/gems/pgsync-0.7.0
```

```
pgsync --schema-first
  From: db_1 on server:port
  To: db_2 on server:port
  ⠋ Syncing schemapg_restore not found
```

**Comment by ankane** [comment]
Hey @aliammaar, you can install `pg_restore` on Ubuntu with:

```sh
sudo apt-get install postgresql-client
```

**Comment by aliammaar** [comment]
> Hey @aliammaar, you can install `pg_restore` on Ubuntu with:
> 
> ```shell
> sudo apt-get install postgresql-client
> ```

It worked, thanks much again 🎉

**Comment by nathancolgate** [comment]
FWIW: We ran into this same issue with `v0.7.0` and `v0.7.1` of the docker images:

> When running `pg_sync` with `--schema-first` using `ankane/pgsync` from the docker hub registry I get a `pg_restore not found` error.

Which is very strange, because we could shell into the container and get a successful response from `which pg_restore`. So it's in there, but also not in there as far as Ruby is concerned?

We resolved the problem by downgrading to the `v0.6.8` tag.

**Comment by ankane** [comment]
Hey @nathancolgate, I'm not able to reproduce.

**Comment by nathancolgate** [comment]
@ankane thanks for trying! If I have time this week, I will try to capture the steps we had in our environment.

**Comment by nathancolgate** [comment]
@ankane We just ran`ankane/pgsync:v0.7.1` successfully as a kubernetes cron job with the `--schema-first` option and had zero issues. 

My guess is we were just having a rough DevOps day. Thanks for the amazing tool.
