### ISSUE TITLE
How to configure yml to copy all-schemas?

### ISSUE THREAD

**Issue by ningningba** [ankane/pgsync#136]
I am creating a pgsync yml file to copy DB schema from one host to the localhost. I could not figure out how to copy all the schemas. The database has two schemas : public and second_schema. Both public and second_schema could be created in my local DB through the pgsync (using the yml file). However, only tables in the public are created in the localhost DB, and the tables in the second_schema are not created. Directly running pysync command with --all-schemas replicates all the tables in all the schemas, but I am trying to figure out how to do that through the yml.

I have tried to specify

schemas:
 - public
 - second_schema

I also tried to specify all_schemas, but none of the yml copies the tables from the second_schema to my local DB. My pgsync version is 0.6.7.

Would you please show me how to copy all the schemas? Many thanks!

**Comment by ankane** [comment]
Hey @ningningba, setting `schemas` should work (and does when I just tried it). If you use the `--debug` option, do you see `second_schema` in the output?
