### ISSUE TITLE
Can we have custom columns in destination DB?

### ISSUE THREAD

**Issue by botzill** [ankane/pgsync#138]
Hi.

I want to sync data from X databases into 1 destination DB. Now, for each table, I want to add a new field that will identify which DB it comes from, can we configure that? All databases have the same tables. I just one to have a single database as output with data from all the other. This final DB will be used in grafana to draw charts.  

Thx.

**Comment by ankane** [comment]
Hey @botzill, it's an interesting idea, but think it's outside the scope of pgsync (closer to an ETL tool).
