### ISSUE TITLE
Error on sync databases, but trying preserve on TO database - No primary key (PgSync::Error)

### ISSUE THREAD

**Issue by andrebetiolo** [ankane/pgsync#144]
Hello, I'm trying to update my sandbox database (TO database), but I didn't want the data from the destination database to be deleted, as I have, for example, a test user inside the users table, which I need not can be deleted.

The command I used was:

`pgsync --from $DATABASE_FROM_URL --to $DATABASE_TO_URL --to-safe --defer-constraints-v2 --preserve --debug`

Error:

From: postgres on a:5432
To: postgres on b:5432
[to] SHOW server_version_num
[from] SELECT unnest(current_schemas(true)) AS schema
[from] SELECT table_schema AS schema, table_name AS table FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('information_schema', 'pg_catalog') ORDER BY 1, 2
[to] SELECT table_schema AS schema, table_name AS table FROM information_schema.tables WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('information_schema', 'pg_catalog') ORDER BY 1, 2
[from] SELECT table_schema AS schema, table_name AS table, column_name AS column, data_type AS type FROM information_schema.columns WHERE is_generated = 'NEVER' ORDER BY 1, 2, 3
[to] SELECT table_schema AS schema, table_name AS table, column_name AS column, data_type AS type FROM information_schema.columns WHERE is_generated = 'NEVER' ORDER BY 1, 2, 3
[to] SELECT nspname AS schema, relname AS table, pg_attribute.attname AS column, format_type(pg_attribute.atttypid, pg_attribute.atttypmod), pg_attribute.attnum, pg_index.indkey FROM pg_index, pg_class, pg_attribute, pg_namespace WHERE indrelid = pg_class.oid AND pg_class.relnamespace = pg_namespace.oid AND pg_attribute.attrelid = pg_class.oid AND pg_attribute.attnum = any(pg_index.indkey) AND indisprimary
[from] SELECT nt.nspname as schema, t.relname as table, a.attname as column, n.nspname as sequence_schema, s.relname as sequence FROM pg_class s INNER JOIN pg_depend d ON d.objid = s.oid INNER JOIN pg_class t ON d.objid = s.oid AND d.refobjid = t.oid INNER JOIN pg_attribute a ON (d.refobjid, d.refobjsubid) = (a.attrelid, a.attnum) INNER JOIN pg_namespace n ON n.oid = s.relnamespace INNER JOIN pg_namespace nt ON nt.oid = t.relnamespace WHERE s.relkind = 'S'
[to] SELECT nt.nspname as schema, t.relname as table, a.attname as column, n.nspname as sequence_schema, s.relname as sequence FROM pg_class s INNER JOIN pg_depend d ON d.objid = s.oid INNER JOIN pg_class t ON d.objid = s.oid AND d.refobjid = t.oid INNER JOIN pg_attribute a ON (d.refobjid, d.refobjsubid) = (a.attrelid, a.attnum) INNER JOIN pg_namespace n ON n.oid = s.relnamespace INNER JOIN pg_namespace nt ON nt.oid = t.relnamespace WHERE s.relkind = 'S'
event_types: Extra columns: magnitude
events: Extra columns: magnitude
[to] BEGIN
[to] SELECT table_schema AS schema, table_name AS table, constraint_name FROM information_schema.table_constraints WHERE constraint_type = 'FOREIGN KEY' AND is_deferrable = 'NO'
[to] SET CONSTRAINTS ALL DEFERRED
[from] BEGIN
/usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:128:in `sync_data': No primary key (PgSync::Error)
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:26:in `block (3 levels) in perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:321:in `maybe_disable_triggers'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:25:in `block (2 levels) in perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:190:in `handle_errors'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:24:in `block in perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:178:in `with_notices'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/task.rb:23:in `perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:252:in `block (2 levels) in run_tasks'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:349:in `block in work_direct'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:527:in `with_instrumentation'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:348:in `work_direct'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:285:in `map'
        from /usr/local/bundle/gems/parallel-1.21.0/lib/parallel.rb:238:in `each'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:248:in `block in run_tasks'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:287:in `block (2 levels) in maybe_defer_constraints'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:151:in `block in transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:150:in `transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:150:in `transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:286:in `block in maybe_defer_constraints'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:151:in `block in transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:150:in `transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/data_source.rb:150:in `transaction'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:272:in `maybe_defer_constraints'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:244:in `run_tasks'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/table_sync.rb:28:in `perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/sync.rb:67:in `perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/client.rb:25:in `perform'
        from /usr/local/bundle/gems/pgsync-0.6.8/lib/pgsync/client.rb:34:in `start'
        from /usr/local/bundle/gems/pgsync-0.6.8/exe/pgsync:7:in `<top (required)>'
        from /usr/local/bundle/bin/pgsync:23:in `load'
        from /usr/local/bundle/bin/pgsync:23:in `<main>'

**Comment by gonssal** [comment]
Sorry to comment on a close issue, but I think it's preferrable than opening a new one in this case. I'm not using the `--preserve` option and I'm having this same error, `sync_data': No primary key (PgSync::Error)`.

The error is caused by a table that has no primary key, isn't it possible to sync tables without them? I'm only using the `--defer-constraints` option.
