### ISSUE TITLE
Feature proposal: Preserve old value when updating existing rows

### ISSUE THREAD

**Issue by msimav** [ankane/pgsync#148]
Hey @ankane

First of all, thank you for this great tool!

We are using pgsync to move data between our production and beta environments. But we want to exclude some fields from updates for existing rows. Let's say we have a table `tbl1` with 3 columns `a`, `b`, and `c`. We want to insert all fields but only update `a`, and `b`.

To do that, we can add a new configuration similar to `data_rules` and remove the fields that match any rule from the `ON CONFLICT DO UPDATE` section.

Example config would look like this
```yaml
exclude_from_update:
    - tbl1.c
```

And generated SQL would look like this
```sql
INSERT INTO tbl1 (id, a, b, c)
(SELECT id, a, b, c FROM pgsync_886903156)
ON CONFLICT ("id") DO UPDATE SET a = EXCLUDED.a, b = EXCLUDED.b
```

Does that make sense? If so, we'd like to contribute a PR and implement this feature.

**Comment by ankane** [comment]
Hey @msimav, have you tried the `untouched` data rule? I think it should do what you're describing.

**Comment by msimav** [comment]
It sounds like that but it does not do what we want. I added a failing test case to show the problem on https://github.com/msimav/pgsync/commit/19a6537012c2975717a4576e33d8599ded57ce43

In the code, `untouched` just does a `quote_ident(column)` so I believe it is used for undoing a data rule for a specific field. 
For example, to put a random string into all token fields but on the user table
```yaml
data_rules:
  users.token: untouched
  token: random_string
```

To make the test case pass, we can exclude untouched fields from the `ON CONFLICT DO UPDATE` clause like https://github.com/msimav/pgsync/commit/932d9726ab9cfaa7c2d19c0451ebd4e2e0cf7ef8

If you think `untouched` should work this way, I can create a PR for this

**Comment by ankane** [comment]
My bad, you're exactly right - `untouched` is for undoing a data rule.

Excluding columns is an interested idea, but don't think it's something I'd like to add/support right now.

**Comment by msimav** [comment]
It is okay. I created a fork to implement the changes we need.

I created a PR to share the changes with you but feel free to close it.
