### ISSUE TITLE
How to sync table with self referencing foreign keys?

### ISSUE THREAD

**Issue by andrepiske** [ankane/pgsync#153]
Hello and thanks for the great project!

I have the following scenario. Let's say I have the following table:
```sql
CREATE TABLE posts (
  id BIGINT PRIMARY KEY,
  linked_post_id BIGINT,
  FOREIGN KEY (linked_post_id) REFERENCES posts (id)
);
```

So the column `linked_post_id` (can be null) is a self referencing foreign key.

pgsync fails to sync this even with `--defer-constraints`. Using `--disable-integrity` works but then it throws away all integrity guarantees.

If I could instruct pgsync to run this in "two passes", the first one having `WHERE linked_post_id IS NULL` and the second pass then `WHERE linked_post_id IS NOT NULL`, this would work. I can't seem to find a way to do this though. Is it possible at all?

If not possible, are there any planned features for this or how would it look like?

**Comment by ankane** [comment]
Hey @andrepiske, can you share the error message you're seeing, as well as expand the example above to reproduce the issue?

**Comment by ankane** [comment]
Created a template to make things easier to reproduce: https://gist.github.com/ankane/3470fffd422f57b75e1bd839d4835c5c

**Comment by andrepiske** [comment]
I appreciate the quick response and template you created, but I have to ask sorry since it seems I was mistaken and my issue isn't something with pgsync.

Closing this issue as it's not really relevant anymore.
