### ISSUE TITLE
Need Suggestion how to make data render from second table in no time if we are saving 100 rows after callback 

### ISSUE THREAD

**Issue by snawar92** [ankane/pgsync#154]
Hi, i have a question @ankane if i move pgsync script in background jobs, will it create issue, eg I am performing submissions for a survey and it has many submission_answers will those create an issue for 1000 parallel users to migrate data for each submission, I am wondering how i can handle that, should I do it in background job or do it after_commit/save callback , what is happening we are showing results of that submission after save of submission to each submitter, how we can do realtime sync with no delay to show data from the second table

**Comment by snawar92** [comment]
@ankane

**Comment by ankane** [comment]
Hey @snawar92, check out #92.
