### ISSUE TITLE
Info | is pgsync adequate for master-master replication?

### ISSUE THREAD

**Issue by dberardo-com** [ankane/pgsync#155]
I am looking for ways to replicate data from 2 postgres nodes in a multi-master fashion.

I don't care much about conflict resolution and data losses since i would like the system to work on a row-level replication and always take the last update found per row, in case of conflicts.
Also schema changes would be quite uncommon in my setup.

Currently my research points to CDC systems like Debezium. That works quite well, but i could only manage to use it for manual sync between nodes and not in a automated way, since i always run in infinite write-write loops between the 2 nodes.

So my question here is can pgsync cover this use case?

**Comment by ankane** [comment]
No, pgsync isn't designed for this.
