### ISSUE TITLE
materialized views

### ISSUE THREAD

**Issue by masterkain** [ankane/pgsync#158]
hello,
any way to support syncing materialized views?

**Comment by ankane** [comment]
Hey @masterkain, pgsync doesn't support it directly, but you can sync the underlying tables, and then manually refresh the views. Someone could probably create a fork / wrapper script to:

1. Get the view definitions
2. Parse out the tables (with a library like pg_query)
3. Sync those tables
4. Refresh the views

But I think it's outside the scope of pgsync right now.
