### ISSUE TITLE
Error dumping schema: "Syntax error"

### ISSUE THREAD

**Issue by A140197** [ankane/pgsync#16]
pgsync version: 0.3.7

Gday. I'm trying to use pgsync for the first time and I get this error:

```
$ pgsync --config .pgsync-app_db.yml --schema-only --debug
From: application on <host-omitted>:5432
To: p2p_analysis on localhost:5432
* Dumping schema
sh: 1: Syntax error: "(" unexpected
Completed in 2.7s
```

When I login using psql I see the following:

```
psql "postgres://<URI-omitted>/application"
psql (9.5.8, server 9.5.4)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

application=> \d
```

Any help appreciated!

**Comment by lgwaustralia** [comment]
Hey Jay,  Make sure to urlencode your password.  That tripped me up.. things like ( or @ will break the process.  Hope that helps!

**Comment by A140197** [comment]
Hi. My password is urlencoded and I can tell the login is working: if I try an incorrect password I get a different result.

Eg with incorrect password:
```
$ pgsync --config .pgsync-equipment_db.yml --schema-only aemo_nem
From: <host-omitted>.amazonaws.com:5432
To: p2p_analysis on localhost:5432

FATAL:  password authentication failed for user "agl"
FATAL:  password authentication failed for user "agl"
```

With correct password:
```
$ pgsync --config .pgsync-equipment_db.yml --schema-only aemo_nem
From: <host-omitted>.amazonaws.com:5432
To: p2p_analysis on localhost:5432
* Dumping schema
sh: 1: Syntax error: ")" unexpected
Completed in 0.6s
```

pgsync works for me on a different database. This problem appears to be specific to a particular source database / schema. Unfortunately the schema is proprietary so I can't post it here.

Is there any way I can diagnose it further?

Cheers,
Jay.

**Comment by ankane** [comment]
Hey @A140197, I noticed pgsync wasn't escaping database urls in the shell. Can you try master?

```sh
gem install specific_install
gem specific_install ankane/pgsync
```

**Comment by A140197** [comment]
Hi @ankane ,

Yep 0946f61 fixed the issue.

I'm hoping to use pgsync from now on.

Cheers!
Jay.

**Comment by ankane** [comment]
@A140197 I believe this change breaks properly encoded urls, so I've reverted. From the error above, I have a feeling yours were not.
