### ISSUE TITLE
Add `--append` Option

### ISSUE THREAD

**Issue by archongum** [ankane/pgsync#161]
Hi, `--preserve` needs primary key, is there possible adding `--append` to allow append rows directly? 
Here is my use case:
1. Delete `type='A'` from target table (via psql or jdbc manually, of course)
2. Sync `type='A'` from source table to target table

There is no primary key in both source table and target table.

**Comment by ankane** [comment]
Hey @archongum, thanks for the suggestion, and sorry for the delay. It's an interesting idea for a new type of sync, but not something I'd like to support right now.
