### ISSUE TITLE
Incremental Sync

### ISSUE THREAD

**Issue by Nilanth** [ankane/pgsync#162]
Is possible to sync data incrementally?

**Comment by ankane** [comment]
Hey @Nilanth, if you have a column on the table that keeps track of the last time a record was updated, you can do something like:

```sh
pgsync products "where updated_at > NOW() - INTERVAL '1 day'"
```

Or if you have a large, append-only table with a numeric, incrementing primary key, you can use:

```sh
pgsync large_table --in-batches
```
