### ISSUE TITLE
Consider renaming the repository

### ISSUE THREAD

**Issue by 13hannes11** [ankane/pgsync#167]
The name pgsync is used up by two tools. This one and one to sync with elastic search. This makes it quite confusing when trying to find the tool via search engine, therefore it might be a good idea to choose another name for this tool, if you deem that to still be easily feasible.

The mentioned tool you can find here: https://github.com/toluaina/pgsync

**Comment by ankane** [comment]
Hey @13hannes11, since this project has been around for almost 7 years, I don't think it makes sense to change.
