### ISSUE TITLE
to_safe Error with localhost and shell exec

### ISSUE THREAD

**Issue by mFeigeInvia** [ankane/pgsync#169]
Hi,
we are facing a issue with url interpretation. This happens in multiple pgsync versions(0.7.2-0.6.8) on linux and osx. But with older installations its working

Config yaml
```yaml
(to: $(echo "postgresql://postgres:changeme@localhost:5432")/test_db)
```
Result:
```sh
Danger! Add `to_safe: true` to `.pgsync.yml` if the destination is not localhost or 127.0.0.1
```
Any suggestions?

Thx

**Comment by ankane** [comment]
Hey @mFeigeInvia, will figure out a fix for this project, but for now, downgrading the `pg` gem should fix it.

```
gem uninstall pg -v 1.4.4
gem install pg -v 1.4.3
```

**Comment by mFeigeInvia** [comment]
> Hey @mFeigeInvia, will figure out a fix for this project, but for now, downgrading the `pg` gem should fix it.
> 
> ```
> gem uninstall pg -v 1.4.4
> gem install pg -v 1.4.3
> ```
> 
> Note: This affects all `to` urls that use `localhost`

awesome, will this be added to the pgsync.gemspec  for a new release?

**Comment by ankane** [comment]
Just pushed 0.7.3. Thanks for reporting!

**Comment by mnort9** [comment]
Running into this issue in 0.8.0. Tried downgrading to 0.7.3, same result. Works when adding `to_safe` flag. 

```
pgsync (0.8.0)
pg (1.5.9)
```
```yml
from: $(heroku config:get DATABASE_URL)?sslmode=require
to: postgres://localhost:5432/app_db
```
