### ISSUE TITLE
create missing tables

### ISSUE THREAD

**Issue by benlieb** [ankane/pgsync#170]
Is there a way to create missing tables when syncing?

I'm just getting an error that the destination table doesn't exist...

**Comment by ankane** [comment]
Hey @benlieb, check out the schema section of the readme.

**Comment by benlieb** [comment]
@ankane thanks for the quick response, but I'm not sure this fully answers my question.

I seems if I want the table structure to be created I can do something like this:

```
pgsync table1 --schema-first
```

And that means that if there is data on the `to.table1` then it will be erased and replaced with `from.table1`. Is that right?

Ideally for me there would be a flag that I could pass that would just create the table if missing, and otherwise sync as normal. But I guess the above approach is for reconciling changes in the schema, not really missing tables. Ideally I would use

```
pgsync table1
```
 
Would behave like this in my opinion, or an explicit flag like

```
pgsync table1 --create-if-missing
```

As it is I'll have to run different commands depending on whether the table exists or not. I'm writing rake tasks for automating tasks and it will require some knowledge/intervention on my part because it's not trivial to programatically determine if the remote table exists or not.
