### ISSUE TITLE
Cannot sync tables with generated columns

### ISSUE THREAD

**Issue by MisterBolt** [ankane/pgsync#172]
Hi,

Is there possible to ignore generated/virtual columns during pg_sync or do you know any workaround?
```
PG::InvalidColumnReference: ERROR:  column "roles_count" is a generated column
DETAIL:  Generated columns cannot be used in COPY.
```
Information from https://pgdash.io/blog/postgres-12-generated-columns.html saying that it is possible to COPY generated columns:
```
Copy and pg_dump: The values of generated columns are omitted in the output of “pg_dump” and “COPY table” 
commands, as it is unnecessary. You can explicitly include them in COPY using COPY (SELECT * FROM t) TO STDOUT 
rather than COPY t TO STDOUT.
```

**Comment by ankane** [comment]
Hi @MisterBolt, support for generated columns was added in 0.6.6. Please use the script from the new issue template to reproduce if you're seeing issues.
