### ISSUE TITLE
Create missing tables or missing columns without wiping datas

### ISSUE THREAD

**Issue by ifleg** [ankane/pgsync#178]
Hi,
-- short story --
Is there a way to create missing tables and create missing columns without wiping data in the destination DB ?

-- long story --
I have a master DB (production) and a local replica (for users). 
Master DB evolve regularly and local replica DB needs to be updated with new raws from the master.
Moreover in the local replica, users can add new records (which are not in the master).
The separation between master datas and replicas is done by using different values for primary keys (basically pk  in the master are between 0 and 4500000000000000000 and pk for user data inserted in the local replica are over 4500000000000000000 - I use bigint -).
Thus the syncro is done using groups defined by :
```
groups:
  mygroup:
    mytable: "where id_something < 4500000000000000000"
```

Now, if a new table is added in the master DB, I cannot find a way to add it automatically using pgsync. Because if I use --schema it will wipe the users data.
Same thing if a column is added in a table in the master DB, I cannot see how to add it in the replica without wiping it !
I guess that combining --schema-first and --preserve should be a way (obviously it should be restricted only to creation of missing tables and missing columns and fails if existing columns change of type or if columns vanished), thus maybe a  a --schema-append-missing flag should be created for clarity.

**Comment by ifleg** [comment]
For missing tables I think that 
pgsync new-table --schema-first
is a solution. 
Thus my question/request remains for new columns !

**Comment by ankane** [comment]
Hey @ifleg, pgsync doesn't support syncing only missing tables (`--schema-first` syncs all tables) or missing columns. The schema sync is very basic by design - you'll want to use a schema migration tool to manage the schema in most cases.
