### ISSUE TITLE
Allow dry run

### ISSUE THREAD

**Issue by boxydog** [ankane/pgsync#185]
Thanks for your work on pgsync.

I see the `--debug` option allows showing the SQL used for syncing.

Is it possible to add another flag for a dry run, i.e. don't change anything in the destination?

Then we could see what will change.

**Comment by boxydog** [comment]
Although I see it just wipes out a table and recopies it, so I wouldn't see in detail what changes. Maybe this is less useful than I thought.

**Comment by ankane** [comment]
Hi @boxydog, you can use the `--list` option to see which tables will be synced.

**Comment by boxydog** [comment]
Thanks!
