### ISSUE TITLE
Sync the database by using RPC or HTTP API

### ISSUE THREAD

**Issue by JohnnyRacer** [ankane/pgsync#188]
Hello, does there exist a way to call the sync operation over RPC or HTTP using an API call? It's a bit of a pain having to use `cron` to update the databases periodically.

**Comment by JohnnyRacer** [comment]
I'm using the docker image so running the `pgsync` command from my other containers is a bit inconvenient, if there's a workaround to this it would be much appreciated.

**Comment by ankane** [comment]
Hi @JohnnyRacer, you could create a service that wraps pgsync for this.
