### ISSUE TITLE
pgsync data sync method 

### ISSUE THREAD

**Issue by Akshaypatil619** [ankane/pgsync#194]
Hi,

We are planning to use pgsync one of our project on postgresql on azure to sync data from one postgresql db to another postgresql db. but i do want to understand how does data gets copy I mean does it copy incrementally or copy whole data whenever I run pgsync command. 

Thank you

**Comment by Akshaypatil619** [comment]
@ankane @sandeep45 @stem @ogerman @mharju @ogerman @kwent @aliou @arshsingh @joehorsnell @pyrliu

**Comment by ankane** [comment]
Hi @Akshaypatil619, the whole table is copied by default. There's an option to sync specific rows, but if you're looking for incremental updates in general, you'll want to use another project.

Also, please don't tag contributors in issues like above. Locking to prevent additional noise.
