### ISSUE TITLE
Incremental update and foreign keys

### ISSUE THREAD

**Issue by Akshaypatil619** [ankane/pgsync#195]
Hi @ankane ,

In issue 144 you mentioned to use another tool for incremental update or sync do you any gem or git repo this will help us. also for foreign key  which method is reliable defer constraint or sync data one by one tables?

**Comment by ankane** [comment]
Hi @Akshaypatil619, there are tools for [trigger-based replication](https://wiki.postgresql.org/wiki/Trigger-based_Replication) like [Bucardo](https://github.com/bucardo/bucardo), and probably ones for logical replication as well. For foreign keys, both methods should be reliable.
