### ISSUE TITLE
All Logs are Going to Stderr

### ISSUE THREAD

**Issue by ofiliojo** [ankane/pgsync#197]
Hi @ankane,

Why are all logs configured to go stderr rather than stdout? Is it possible to configure the log so that only errors go to stderr and regular logs go to stdout? I'm happy to make a PR if this is something you're open to.

Btw, thanks for this tool, it has been very useful to my team.

**Comment by ankane** [comment]
Hi @ofiliojo, stderr is commonly used for all log messages (not just errors), so it's not something I'd like to change.

**Comment by ofiliojo** [comment]
Hey @ankane, thanks so much for the quick response. Please allow me to more clearly articulate my problem statement. 

Most third-party log management systems make determinations as to the severity of the logs based on the standard stream definitions (i.e. STDERR is treated more severely than STDOUT). This leads to a much greater debugging difficulty when there are issues. Typically, users expect there to be some amount of tiering of service output, where errors that require the user to take action are separated from logs used to inform the user of expected runtime behavior.

The Logger in Ruby’s STL allows us to specify multiple loggers going to STDERR and STDOUT, in addition to including six of the eight standard linux log severity levels. I understand that it is quite a lift for pgsync, but the community as a whole would benefit from this because it would eliminate the need for any bespoke code to provide custom filters integration with standard log management solutions.

Again, I would be more than happy to submit this PR if you would be amenable to it.
