### ISSUE TITLE
Deadlock Issue with --disable-user-triggers option

### ISSUE THREAD

**Issue by mehmetsagdur** [ankane/pgsync#200]
Hi,

I have a usage like the following:

```sh
pgsync public-table --disable-user-triggers --jobs 2 --config ~/../app/config.yml
```

I'm using it this way because I don't have a superuser account in my DigitalOcean database, so I can't use other options like --disable-integrity, etc. When I use it like this, the first table, no matter which one, always results in a deadlock. However, when I use --debug, I don't encounter any issues. Do you have any idea why I might be experiencing this problem?

If I use --defer-constraints I get the following error.

✔ countries - 0.0s
✖ cities (cannot ALTER TABLE "cities" because it has pending trigger events)
✖ districts (current transaction is aborted, commands ignored until end of transaction block)
✖ neighborhoods (current transaction is aborted, commands ignored until end of transaction block)

Thank you.

**Comment by ankane** [comment]
Hi @mehmetsagdur, please use the new issue script to show what you're trying to do.
