### ISSUE TITLE
Django - Similar Project

### ISSUE THREAD

**Issue by ACPK** [ankane/pgsync#21]
Do you know of any similar projects for Django / Python apps?

**Comment by ankane** [comment]
Hey @ACPK, `pgsync` works with any language. It's just a command line tool.

**Comment by ACPK** [comment]
@ankane - Do I owe you a thank you card?

**Comment by ankane** [comment]
Ha :)

**Comment by ACPK** [comment]
@ankane  - " gem install pgsync" doesn't do anything inside of my Django application. It ran for 1 hour, but nothing happened.

**Comment by ankane** [comment]
You should be able to run the command anywhere on your computer/server. I'd try again - I've never seen `gem install` hang for more than a few seconds.

**Comment by ACPK** [comment]
@ankane - Gem install works inside my Rails application but nowhere else.

**Comment by ankane** [comment]
Can you install other gems besides pgsync in other directories?
