### ISSUE TITLE
Throw on invalid .pgsync.yml

### ISSUE THREAD

**Issue by Garrett-R** [ankane/pgsync#211]
It would be nice if `pgsync` threw when `.pgsync.yml` was invalid.  While QAing on temporary DBs, an LLM just hallucinated that `tables` was a config option (made feature request in #210 BTW).

`pgsync` happily ran despite an unrecognized config.  Indeed you can add this to your config:

```sh
foo:
  - bar
```

and it'll still run.  I think it's more conventional and safer for tools not to run if there's hogwash in the config.

**Comment by ankane** [comment]
Hi @Garrett-R, thanks for the suggestion. However, this would affect YAML aliases.

**Comment by Garrett-R** [comment]
Ah good to know! 

It does seem though that, at least in theory, this package should be able to consume one of its config files and answer the question "is this a valid config file?" even while supporting YAML aliases.  No idea how challenging that would be though.
