### ISSUE TITLE
PostgreSQL 9.6 to 16

### ISSUE THREAD

**Issue by Abraka** [ankane/pgsync#215]
Hi,
question about sync between psql v9.6 and v16. It is possible to sync/migrate between those two?
Thx.

**Comment by ankane** [comment]
Yes, that should work.

**Comment by Abraka** [comment]
Great, and its possible to make full sync, lets say week before final switch and just right before switch get incremental sync = difference between that time period/week?

**Comment by ankane** [comment]
It can do partial syncs, but not a diff between tables, so you'll probably want to use a different tool if that's what you need. I'd recommend trying it out if you have additional questions about functionality.

**Comment by Abraka** [comment]
I will try it, for sure. Btw. any recommendation for that other tool? Thx.
