### ISSUE TITLE
Got a lot of "canceling statement due to conflict with recovery" and "Deadlock detected" Errors when sync the database

### ISSUE THREAD

**Issue by HieronyM** [ankane/pgsync#216]
I was trying to sync my production database to the dev environment, but I keep getting a lot of errors like "canceling statement due to conflict with recovery", "Deadlock detected" and "violates foreign key constraint"

Is there anything I can do to minimize the error? maybe setting up some parameter or some configuration on the source or target database?

<img width="1460" alt="image" src="https://github.com/ankane/pgsync/assets/8222055/206a74d9-7ae3-408e-88a1-5cefb6f93d4a">

**Comment by ankane** [comment]
Hi @HieronyM, check out [this](https://stackoverflow.com/questions/14592436/postgresql-error-canceling-statement-due-to-conflict-with-recovery) for how to address `canceling statement due to conflict with recovery` and the readme for options on foreign keys.
