### ISSUE TITLE
How to sync only a specific schema?

### ISSUE THREAD

**Issue by pkordylewski** [ankane/pgsync#22]
Hey!

i've seen that since version 0.3.5 there is a possibility to sync a specific schema and not public. But it's not documented how it can be used. Can you provide an example?

Cheers,
Patryk

**Comment by ankane** [comment]
Hey @pkordylewski, right now, the only way is to add a `?schema=otherschema` to your to and from urls (and all tables will use that schema). I think a better solution would be to support:

```sh
pgsync otherschema.table
```

**Comment by pkordylewski** [comment]
Great, Thanks! Will try it out

**Comment by pkordylewski** [comment]
Unfortunately i couldn't get it working. I'm trying to sync a complete schema from one host to another host. I have a config that looks like this:

```
from: postgres://user:pw@remote:5492/dbname?schema=some_schema
to: postgres://user:pw@localhost:5492/dbname?schema=some_schema
```

Connection information are correct and tested. Schema does exist on the remote host but not on the local host. Then i tried to sync the schema first:

```
# pgsync --db myconfig --schema-only
From: dbname on remote:5492
To: dbname on localhost:5492
* Dumping schema
pg_dump: No matching tables were found
pg_restore: [archiver] input file is too short (read 0, expected 5)
Completed in 6.0s
```

Is this use-case supported? `--debug` parameter doesn't show more information.

Thanks for your help

**Comment by ankane** [comment]
Ah, the `schema-only` option doesn't support it right now. I'm happy to accept a PR if you want to add it.

**Comment by pkordylewski** [comment]
Sorry, my ruby skills are limited (read: non existent). But i think i've found another problem. The sequences are also not aware of schemata?

```
/var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:564:in `exec': ERROR:  relation "accounting_types" does not exist (PG::UndefinedTable)
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:564:in `sequences'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:152:in `block (3 levels) in sync_table'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:391:in `with_connection'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:143:in `block (2 levels) in sync_table'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:391:in `with_connection'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:142:in `block in sync_table'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:402:in `benchmark'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:141:in `sync_table'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:127:in `block in perform'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:569:in `each'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:569:in `in_parallel'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/lib/pgsync.rb:126:in `perform'
        from /var/lib/gems/2.1.0/gems/pgsync-0.3.8/exe/pgsync:5:in `<top (required)>'
        from /usr/local/bin/pgsync:23:in `load'
        from /usr/local/bin/pgsync:23:in `<main>'

```

```
    def sequences(conn, table, columns)
      conn.exec("SELECT #{columns.map { |f| "pg_get_serial_sequence(#{escape(quote_ident(table))}, #{escape(f)}) AS #{f}" }.join(", ")}").to_a[0].values.compact
    end
```

This is what lands in my logs:

```
SELECT pg_get_serial_sequence('"accounting_types"', 'accounting_type_handle') AS accounting_type_handle
```
It should look like this (or you need to "`SET search_path TO my_schema, public;`"):

```
SELECT pg_get_serial_sequence('my_schema.accounting_types', 'accounting_type_handle') AS accounting_type_handle;
```
Please note the different quoting.

Cheers,
Patryk

**Comment by ankane** [comment]
Hey @pkordylewski, I think you're right about sequences. It looks like schema support needs revisited. Also, fwiw, the double quotes are optional, so there isn't an issue w/ quotes, just that the schema isn't present.

**Comment by ankane** [comment]
Hey @pkordylewski, both issues with schemas (schema only sync and sequences) are fixed on master.

**Comment by ankane** [comment]
Just pushed out a new version (0.3.9) w/ full support for schemas. Let me know if you still have issues.

**Comment by ACPK** [comment]
@ankane @pkordylewski - Is there a way to download the tables from all schemas? In other words, I would rather not specify which schemas to download.

**Comment by khairnarTK** [comment]
I'm trying to sync specific schema then got error 'invalid URI query parameter: "schema"'

**Comment by ankane** [comment]
Hey @pkordylewski, the latest syntax is

```sh
pgsync sch_prod.*
```

**Comment by khairnarTK** [comment]
Sorry, but not work properly.. 
qtc-006s-MacBook-Pro:~ tushar$ pgsync sch_prod.*
invalid URI query parameter: "schema" 

Any change in URI ' postgres://localhost:5432/testsource?schema=sch_prod'

**Comment by ankane** [comment]
As the error mentions, you need to remove `schema` from the URI.
