### ISSUE TITLE
Consume a lot of Storage size even when the build failed

### ISSUE THREAD

**Issue by HieronyM** [ankane/pgsync#220]
Dear @ankane ,
Thanks for the great tool, I've been enjoying the tools so much.

So I've been trying to sync on my AWS RDS Postgres source database (around 500GB of data), and I realized that at some point the target database will use a lot of disk storage (Hit 2,2 TB even when the sync failed). The command that I run is `time pgsync --truncate --defer-constraints --fail-fast > pgsync-30-april-2024.txt 2>&1 &` which used "--truncate" to truncate existing row. I'm wondering why the target database consumed a lot of disk space even when the sync failed, and there's no significant data change on the source side. I already try to run `vacuum` on Postgres, but it doesn't seem to free up the disk space

**Comment by ankane** [comment]
Hi @HieronyM, I'm not really sure why it would consume that much more space than the source database. I'd try comparing the table sizes for the databases to see if the difference shows up there.
