### ISSUE TITLE
Error while using `in-batches` for table with bytea columns

### ISSUE THREAD

**Issue by marcocastignoli** [ankane/pgsync#221]
Hello, I'm trying to transfer using the `in-batches` option a big table with two bytea columns. I get this error

```
⠋ code
✖ code (function max(bytea) does not exist)
Sync failed for 1 table: code
```

**Comment by ankane** [comment]
Hi @marcocastignoli, the `--in-batches` option only works with numeric primary keys. I've added a note to the docs in the commit above.
