### ISSUE TITLE
Support regex for tables

### ISSUE THREAD

**Issue by hoangquochung1110** [ankane/pgsync#222]
Hi,

Do we have plan to support regex for tables ?

Please use this script to show what you're trying to do when possible. Thanks!

```sh
pgsync '^opportunity' --debug
```

I got error
```sh
Table not found in source: ^opportunity (PgSync::Error)
```

**Comment by ankane** [comment]
Hi @hoangquochung1110, you can currently use wildcards for this.

```sh
pgsync "opportunity*"
```
