### ISSUE TITLE
Support for Role

### ISSUE THREAD

**Issue by raayu83** [ankane/pgsync#225]
Hi,

currently it is not possible to set the --role parameter for pg_dump and pg_restore.
It would be great if this could be configured in the yaml and using command line parameters.
E.g. in my setup my own user doesn't have enough permissions to sync the schema, I'd have to switch roles for that.

Best regards

**Comment by ankane** [comment]
Hi @raayu83, thanks for the suggestion, but I don't think it's common enough to add.
