### ISSUE TITLE
Server Version Mismatch

### ISSUE THREAD

**Issue by HammNCheez** [ankane/pgsync#226]
When running a `--schema-only` sync of a few tables I get the following error message
```
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.2; pg_dump version: 15.4
pg_restore: error: input file is too short (read 0, expected 5)
 ```

I am using a docker version of the utility, but is there a way I can link it to an updated version of the postgres binaries?

Thanks!

**Comment by ankane** [comment]
Hi @HammNCheez, thanks for reporting! Pushed a new image to the `latest` tag with a fix.

**Comment by HammNCheez** [comment]
Pulled new docker version and it is working now. Thanks for the quick turn around.
