### ISSUE TITLE
Support for large objects

### ISSUE THREAD

**Issue by rafaelse** [ankane/pgsync#229]
I've used this tool on some other occasions and it did its job perfectly.

However, on a recent task, I noticed the target database was significantly smaller than the source database after the migration was done. Migrating via pg_dump/pg_restore, the databases ended up occupying the same amount of space. Further investigation showed that the difference in size was due to large objects not being migrated.

Does the tool support migration of large objects? Is there any option I need to activate to support it?

Thanks in advance.

Great tool, btw.

**Comment by ankane** [comment]
Hi @rafaelse, pgsync doesn't support syncing system catalogs like `pg_largeobject` (and I don't think it's common enough / worth the complexity to add), so you'll probably need to use a different tool for this.
