### ISSUE TITLE
Is there any specific reason --jobs can't be used with --disable_integrity_v2

### ISSUE THREAD

**Issue by N-Putting** [ankane/pgsync#234]
Hi,

Is there any specific reason `--jobs` can't be used with `--disable_integrity_v2` other than the check disabling it? Was this just leftover from an issues with `--disable_integrity_v1` that was copied when adding v2?

Check in question: https://github.com/ankane/pgsync/blob/5a26c1e2eda62cd13d33734d2480baefbbb87dd4/lib/pgsync/table_sync.rb#L233

I would have thought by disabling all triggers it would have been okay to have more than one job as systems like AWS's DMS use it (`SET LOCAL session_replication_role = replica`) with parallel tables. 

Example script:

```sh
pgsync -j 10 --schema-first --schemas public --disable-integrity-v2 --from $source_db --to $target_db --fail-fast
```

I was going to try removing the check and seeing if there was any issue.

**Comment by ankane** [comment]
Hi @N-Putting, see the comment above that line of code.

**Comment by N-Putting** [comment]
Thanks for the fast response. That makes sense for most cases.
