### ISSUE TITLE
Database connection string being parsed not properly when contains @ symbol

### ISSUE THREAD

**Issue by deydinov** [ankane/pgsync#236]
Hi,

Passwords to my databases contain @ symbol which leads to connection issue like 

`
could not translate host name "$$$$W0rd01@db_host" to address: Name does not resolve
`

this is a example of connection string from yml file.

from: postgres://user:Superp@$$W0rd01@db_host:5432/db_name

My I please ask you to fix this?

**Comment by ankane** [comment]
Hi @deydinov, special characters need to be URL-encoded like with psql.

**Comment by deydinov** [comment]
Thank you!
