### ISSUE TITLE
Schema sync fails because of `ArgumentError: Malformed version number string`

### ISSUE THREAD

**Issue by beatak** [ankane/pgsync#28]
On this line:
https://github.com/ankane/pgsync/blob/master/lib/pgsync/data_source.rb#L119

With Ubuntu that I use returns `psql (PostgreSQL) 10.3-1.pgdg16.04+1` (or something) and it fails.

**Comment by ankane** [comment]
Hey @beatak, thanks for reporting 👍 The `psql` version check is now more robust on master.

**Comment by beatak** [comment]
Thx for the fix!
