### ISSUE TITLE
How to handle credentials?

### ISSUE THREAD

**Issue by matejvelikonja** [ankane/pgsync#3]
What is the best way to handle credentials in `.pgsync.yml` file? I would like to keep this file in git, so it's not really good to have there database username and password.

How would you suggest doing this?

**Comment by mada41** [comment]
how about use env variable?

**Comment by matejvelikonja** [comment]
and how do you access env variables from yml?

**Comment by tgezginis** [comment]
@matejvelikonja you can do like this;

~/.bash_profile or ~/.bashrc or ~/.zshrc
`export DATABASE_URL="postgres://user:password@host:port/dbname"`

.pgsync.yml
`from: $(echo $DATABASE_URL)`

**Comment by hendricius** [comment]
I added a PR that supports parsing ERB templates in the `.yml` file. https://github.com/ankane/pgsync/pull/4

**Comment by ankane** [comment]
Thanks for answering @tgezginis 💯
