### ISSUE TITLE
can we compare tables from SQL server and Postgres ?

### ISSUE THREAD

**Issue by mlotfi2005** [ankane/pgsync#30]
I just installed the gem, then did 

 pgsync --setup
C:/Ruby24-x64/lib/ruby/2.4.0/psych.rb:472:in `initialize': Bad file descriptor (Errno::EBADF)

Thanks,

**Comment by ankane** [comment]
Hey @mlotfi2005, not sure the subject matches the description. Someone else reported this error in #20, but am unable to reproduce.

**Comment by ankane** [comment]
Cleaning up stale issues
