### ISSUE TITLE
Does pgsync support between different pg version sync data?

### ISSUE THREAD

**Issue by wps353** [ankane/pgsync#31]
I want to sync some table from pg 9.1.9 to pg 9.6.8,but it's not work.
and some error log as following:

```
/usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/data_source.rb:145:in `conninfo': undefined method `conninfo_hash' for #<PG::Connection:0x0000000200ab20> (NoMethodError)
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/data_source.rb:19:in `host'
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/client.rb:47:in `sync'
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/client.rb:24:in `perform'
	from /usr/local/share/gems/gems/pgsync-0.4.0/exe/pgsync:5:in `<top (required)>'
	from /usr/local/bin/pgsync:23:in `load'
	from /usr/local/bin/pgsync:23:in `<main>'
```
Tks
Best regards。

**Comment by ankane** [comment]
Hey @wps353, it is supported. I think it may be an issue with the pg gem version. Can paste the output of:

```sh
gem list pg
gem install pg
```

And try the sync again?

**Comment by wps353** [comment]
Hey , i had checked it installed the pg gem version,but the error is still here.
 detail log as following:
`[root@monitor_roy ~]# gem list pg

*** LOCAL GEMS ***

pg (1.0.0)
pgsync (0.4.0)
[root@monitor_roy ~]# gem install pg
Building native extensions.  This could take a while...
Successfully installed pg-1.0.0
Parsing documentation for pg-1.0.0
1 gem installed
[root@monitor_roy ~]# pgsync roy_test_hobby
/usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/data_source.rb:145:in `conninfo': undefined method `conninfo_hash' for #<PG::Connection:0x00000001cda9c8> (NoMethodError)
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/data_source.rb:19:in `host'
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/client.rb:47:in `sync'
	from /usr/local/share/gems/gems/pgsync-0.4.0/lib/pgsync/client.rb:24:in `perform'
	from /usr/local/share/gems/gems/pgsync-0.4.0/exe/pgsync:5:in `<top (required)>'
	from /usr/local/bin/pgsync:23:in `load'
	from /usr/local/bin/pgsync:23:in `<main>'`

**Comment by ankane** [comment]
Thanks @wps353. I'm not sure why the `PG::Connection` object doesn't have that method. Do you get the same result in irb?

```sh
irb
```

And

```ruby
require "pg"
PG::Connection.new.conninfo_hash
```

**Comment by wps353** [comment]
I had install pgsync on other Linux server which had installed PostgreSQL Server,and it's work.
i'm not sure why did this happen.

**Comment by iepair** [comment]
@wps353  - Did you find the root cause as I also hit this issue?
