### ISSUE TITLE
Disable trigger

### ISSUE THREAD

**Issue by guilhermeyo** [ankane/pgsync#34]
Hello, I have a problem to do a table sync.
I call it cards and in it I have a column called cover_id and can be null the problem occurs when I have the id of a filled image, it ends up not doing the sync because it says that it did not find the fk in the table of images, but the table of images belongs to the table of cards so I end up falling into the same problem when doing table images sync.

I was able to solve this problem by disabling the trigger of the cards table
``ALTER TABLE cards DISABLE TRIGGER ALL;``

It would be cool if you could do something like
``pgsync cards --preserve --disable-trigger``

sorry for my english

**Comment by ankane** [comment]
Hey @guilhermeyo, thanks for the suggestion, and sorry for the long delay. If you're still interested in this feature, can you create a SQL script with the relevant tables and foreign keys?

**Comment by ankane** [comment]
Hey @guilhermeyo, added an experimental `--disable-all-triggers` option on master, as well as a safer `--defer-constraints` option (which can be used when constraints are deferrable).

Here's a summary of the options: https://github.com/ankane/pgsync#foreign-keys

You can try it out with:

```sh
gem install specific_install
gem specific_install https://github.com/ankane/pgsync.git
```
