### ISSUE TITLE
PG:Connection.new parsing failures

### ISSUE THREAD

**Issue by hopkinschris** [ankane/pgsync#35]
It looks like a minimum version of `0.18.2` is required here in order to take advantage of the [URI connection string enhancement](https://github.com/ged/ruby-pg/blob/master/History.rdoc#v0182-2015-05-14-michael-granger-gedfaeriemudorg). I discovered this when running `0.17.1` and hit a bunch of parsing issues when `PG:Connection.new` was [initiated](https://github.com/ankane/pgsync/blob/master/lib/pgsync/data_source.rb#L97).

https://github.com/ankane/pgsync/blob/9de7a7323e2fe876eac559dd8c6863579a657d58/pgsync.gemspec#L26

**Comment by ankane** [comment]
Thanks @hopkinschris 👍 Updated on master.
