### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by hopkinschris** [ankane/pgsync#36]
I wanted to suggest adding a "tip" to the `README.md` for anyone using `pgsync` via a rake task being run on Heroku.

The [heroku/heroku-buildpack-cli](https://github.com/heroku/heroku-buildpack-cli) is required in order to allow one to run the Heroku CLI w/n a dyno alongside application code. Take the example below:

https://github.com/ankane/pgsync/blob/239941ff2e0f6ef47c6dc27dd938f0ec7603d72e/config.yml#L6

Feel free to shelf this suggestion if it's to specific, totally understand!

**Comment by ankane** [comment]
Hey @hopkinschris, think it may be too specific, but curious to know what the use case is. Production -> staging sync?

**Comment by hopkinschris** [comment]
@ankane No sweat, I understand. Yup, Production → Staging was the use case.

**Comment by ankane** [comment]
I think you could write a short post about it that would be interesting.

**Comment by hopkinschris** [comment]
For those interested, I was looking to have a single `pgsync.yml` file that could be used to sync Production → Development and Production → Staging. The file was setup like:

```yml
# postgres://user:password@host:port/dbname
from: $(heroku config:get DATABASE_URL -a $PGSYNC_FROM_DATABASE)
to: $(echo $PGSYNC_TO_DATABASE)
```
Then `PGSYNC_FROM_DATABASE` and `PGSYNC_TO_DATABASE` could be set as environment variables. However, I needed some additional tasks to be done after the database was synced based on specific types of objects that were newly introduced, e.g. sync some assets over from one s3 bucket to another. I decided to write a simple rake task, something like...

```rake
require 'pgsync'

namespace :db do
  task :sync, %i(command flags) => :environment do |_, args|
    ...
    system("pgsync #{ args[:command].split.join(',') } #{ args.fetch(:flags, '--preserve') }")
    ...
  end
end
```

This now allowed me to run the following locally to sync objects and assets from Production → Development:

```shell
foreman run rake db:sync['foo','--truncate']
```

Next was getting this up on Staging, in order to perform the same task, running:

```shell
heroku run rake db:sync['foo','--truncate'] -a heroku-app-name
```

However, I was then hit with the following message:

```shell
sh: 1: heroku: not found
Command exited with non-zero status:
heroku config:get DATABASE_URL -a $PGSYNC_FROM_DATABASE
```

It was attempting to run this from the config file:

```yml
$(heroku config:get DATABASE_URL -a $PGSYNC_FROM_DATABASE)
```

To make a long story, well long... turns out for my use case I needed to add the [heroku/heroku-buildpack-cli](https://github.com/heroku/heroku-buildpack-cli) buildpack to Staging, which then allowed me to run the Heroku CLI from w/n a dyno alongside the application code.

Anyways, just wanted to share my adventure! ✌️

**Comment by ankane** [comment]
Nice, just need to put in on Medium.
