### ISSUE TITLE
Better documentation for the data protection rules

### ISSUE THREAD

**Issue by daamien** [ankane/pgsync#38]
Hi !

Thanks for this interesting project ! 

I wanted to test some features, especially the sensitive data protection, but I got really confused by the `unique_email` rule. It took me a while to understand that  `unique_email` will only work if the table has a column name "id" (also assuming that this field is unique ).

https://github.com/ankane/pgsync/blob/master/lib/pgsync/table_sync.rb#L181

I feel like the data protection rules should be presented with more details in the README file as most users don't have an "id" column on each table.

Same thing for the rules `random_date`, `random_ip` and `random_letter` which are not random at all 

Or maybe this is a tribute to https://xkcd.com/221/ ;-)

**Comment by stevenharman** [comment]
I wonder if this could be extended to, optionally, leverage `[postgresql_anonymizer](https://gitlab.com/daamien/postgresql_anonymizer) for the data sanitization during sync?

**Comment by ankane** [comment]
@daamien agree the docs are lacking and the outcomes are confusing for some rules. Will try to address soon.

@stevenharman that’s a neat project. I think you could use it as an alternative to data rules, as it would mask with normal sync queries.

**Comment by ankane** [comment]
Just looping back: I improve the data rules on master. Now all rules that start with `random_` have a random aspect, and rules that start with `unique_` use the primary key on the table (and throw a friendly error if there isn't one). Let me know if you either of you have other ideas.

**Comment by ankane** [comment]
This just went out with a new release
