### ISSUE TITLE
OS lib dependencies in README

### ISSUE THREAD

**Issue by fabianofa** [ankane/pgsync#39]
I think it's worth to mention that, on a clean installation of a OS, like Ubuntu 18.04, I had to install a bunch of dependencies:

`sudo apt install postgresql postgresql-server-dev-10`

Otherwise I was getting:

```
Building native extensions. This could take a while...
ERROR:  Error installing pgsync:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/pg-1.1.3/ext
/usr/bin/ruby2.5 -r ./siteconf20181017-28433-1b2jfs9.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
This may be pretty obvious for Ruby developers and who knows the internals of everything, but now showing this information may prevent new developers (as in, new in experience) to understand why it doesn't install.

**Comment by ankane** [comment]
Hey @fabianofa, agreed. Will try to get to that soon

**Comment by ankane** [comment]
Added. If you don't want to install all of Postgres, you can do `sudo apt-get install ruby-dev libpq-dev build-essential`.
