### ISSUE TITLE
How to synchronize data between two databases?

### ISSUE THREAD

**Issue by afuno** [ankane/pgsync#41]
Sorry, but from the README file I didn't understand how to do it.

I have an application that needs to be connected to two databases (main database and mirror). Rails application will work with the main database. But it is necessary to synchronize the data of the main database and the secondary one. Tell me, please, how can this be implemented?

**Comment by ankane** [comment]
Hey @afuno, not sure I follow. Are you asking about real-time syncing?

**Comment by afuno** [comment]
@ankane Desirable. But can with the queue.

**Comment by ankane** [comment]
pgsync isn’t designed for that type of syncing
