### ISSUE TITLE
Wrap TRUNCATE in transaction

### ISSUE THREAD

**Issue by dbechrd** [ankane/pgsync#42]
I could be understanding this incorrectly, but it seems that when I type the filter syntax for pgsync'ing single record incorrectly (e.g. trying to sync a user via `users:123`), pgsync instead decides to try to sync the entire users table. This can be cancelled with Ctrl-C, but unfortunately pgsync also appear to TRUNCATE the users table on localhost before it starts syncing, and the Ctrl-C does not roll back the truncate. As a result, it is immediately and irrecoverably destructive to make a typo in pgsync. According to Postgres docs, TRUNCATE can be wrapped in a DDL transaction. I assume the multi-user sync is already wrapped in a transaction (because when I Ctrl-C I don't end up with only some users, I always end up with 0 users), so perhaps it would be possible to include the TRUNCATE in this same transaction?

I apologize in advance for not having the time to read through the code and possibly having made multiple incorrect assumptions about pgsync or Postgres in this report.

**Comment by ankane** [comment]
Hey @dbechrd, agree it'd be best if it kept its previous state after an error. Unfortunately, running truncate in a transaction locks the table until the transaction completes, which isn't desired.

For the specific case you mentioned, it'd probably be good for pgsync to recognize you're trying to specify a variable for a table or group that doesn't have a variable, and throw an error.

**Comment by ankane** [comment]
There's now an error message if you try to pass a parameter to a table. This should prevent the specific issue you encountered with a typo.
