### ISSUE TITLE
Feature Request: Show row count in output

### ISSUE THREAD

**Issue by dbechrd** [ankane/pgsync#43]
When you sync 0 rows from the remote database, pgsync's output does not signify this in any way (when using groups defined in yml file). It merrily prints out all of the dependent table names and timings as if it were successful, but when you check via Ruby/PG console you don't actually end up with any records. Would be great if pgsync could print the # of rows successfully synced.

**Comment by ankane** [comment]
Not sure I follow the title. pgsync throws an error on failure.

If this is a feature request to show the row count, happy to accept a PR.

**Comment by dbechrd** [comment]
Ah yes, poor title. Syncing 0 rows is a success, but not the desired outcome and a row count would certainly help make it more obvious.

**Comment by ankane** [comment]
Cleaning up stale discussions.
