### ISSUE TITLE
Syncing individual rows fails every time.

### ISSUE THREAD

**Issue by brandondrew** [ankane/pgsync#45]
I didn't know a clear way to succinctly word this in the title, but the issue I'm having affects anything where I give a "SQL template" (for lack of a better term) to a named group.

For example, 

```
💻  pgsync review:1
From: performance on performance-prod-01.ckxih48awmiq.us-west-2.rds.amazonaws.com:5432
To: performance_development_clone on localhost:5432
Table does not exist in source: {"review_workflows"=>"where id = {1}"}
💻  pgsync review_workflows
From: performance on performance-prod-01.ckxih48awmiq.us-west-2.rds.amazonaws.com:5432
To: performance_development_clone on localhost:5432
* Syncing review_workflows
NOTICE:  truncate cascades to table "performance_reviews"
* DONE review_workflows (5.4s)
Completed in 6.5s
```

In the first instance it claims that the `review_workflows` table does not exist, but then when I specify that table, it works, so it's clearly there and pgsync is able to find it.

Here's the relevant section of my .pgsync.yaml:

```
groups:
  review:
    - review_workflows: "where id = {1}"
```

**Comment by ankane** [comment]
Hey @brandondrew, the syntax is slightly off. It should be:

```yml
groups:
  review:
    review_workflows: "where id = {1}"
```

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by brandondrew** [comment]
Thanks! That works now!
