### ISSUE TITLE
Timeout expired with no backtrace or error messages

### ISSUE THREAD

**Issue by choonggg** [ankane/pgsync#50]
pgsync used to work for me and suddenly I'm starting to receive this very vague error.

```
timeout expired
```
I'm able to connect to the database manually via postgres cli so I'm not sure what went wrong here.

**Comment by ankane** [comment]
Hey @choonggg, this means the connection is timing out. You can add `?connect_timeout=60` to the URL for a longer timeout.

**Comment by choonggg** [comment]
hey @ankane thanks for that! Silly me tried `?connectTimeout=60`, sorted this one.

**Comment by blaszczakphoto** [comment]
Where this parameter should be added?
When I added it to `from:` url:
```
from: postgres://user:pass!@ip:5432/dbname?connectTimeout=60
```
 I got this error:
```
invalid URI query parameter: "connectTimeout"
```

**Comment by choonggg** [comment]
@blaszczakphoto I did the same mistake, follow the underscore convention instead.

**Comment by ankane** [comment]
fwiw, the options are consistent with `psql`
