### ISSUE TITLE
SSH to AWS RDS

### ISSUE THREAD

**Issue by ACPK** [ankane/pgsync#52]
What is the recommended way to have Pgsync SSH into a server before connecting to the Postgres database?

**Comment by ankane** [comment]
Hey @ACPK,

You'll want to create an SSH tunnel (add `-N` if you're on Mac).

```sh
ssh -L 63333:localhost:5432 serveruser@server
```

And then point the config url to the tunnel (`localhost:63333`).

```sh
postgres://user@pass:localhost:63333/dbname
```

Check out the [Postgres docs](https://www.postgresql.org/docs/current/ssh-tunnels.html) on the topic for more info.
