### ISSUE TITLE
Getting errors on alpine 3.10 with ruby-2.5.5

### ISSUE THREAD

**Issue by ykostsik** [ankane/pgsync#55]
I'm trying to deploy pgsync in docker alpine v3.10. This version of alpine adds ruby v.2.5.5, that is incompatible with the current pgsync version. BTW, it works with no issues on alpine 3.7 with ruby 2.4.6

/ # pgsync
**Traceback (most recent call last):
        3: from /usr/bin/pgsync:23:in `<main>'`
        2: from /usr/bin/pgsync:23:in `load'`
        1: from /usr/lib/ruby/gems/2.5.0/gems/pgsync-0.4.1/exe/pgsync:3:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/pgsync-0.4.1/exe/pgsync:6:in `rescue in <top (required)>': uninitialized constant PgSync (NameError)**

**Comment by ankane** [comment]
@ykostsik pgsync works fine with Ruby 2.5. It's likely an issue with your Dockerfile. If you narrow down the issue and it still looks like pgsync, please provide additional details

**Comment by ykostsik** [comment]
@ankane Thanks for your comment
Just try to build it using 
```
FROM alpine:3.7

MAINTAINER yk

RUN apk update && apk add --no-cache ruby-irb ruby-dev ruby-rdoc build-base libxml2-dev postgresql-dev libxslt-dev && \
    apk add --no-cache curl vim openrc


RUN gem install pgsync && \
    pgsync --init
```
and change to 3.10 and build again. The second one return the error I mentioned above. ALso tried to rollback ruby to 2.4 in alpine 3.10 -- works OK
