### ISSUE TITLE
invalid URI query parameter: "sslca"

### ISSUE THREAD

**Issue by ACPK** [ankane/pgsync#58]
When I provide a database url with a PEM, I get the following error:

    <database_url>?sslca=config/rds-combined-ca-bundle.pem

Error:

    invalid URI query parameter: "sslca"

**Comment by ankane** [comment]
Hey @ACPK, as the error states, that’s not a valid connection option.

**Comment by ACPK** [comment]
@ankane - How do I connect to the database then as we require it?

**Comment by ACPK** [comment]
@ankane - Is there a reason why we wouldn't be able to use ssl full with PGSync?
