### ISSUE TITLE
second attempt at solving for FK constraints?

### ISSUE THREAD

**Issue by jmmastey** [ankane/pgsync#59]
Hey @ankane, I know this PR has been stalled out for a long time:
https://github.com/ankane/pgsync/pull/6

Would you been amenable to a fixed up branch with the functionality? We'd really love to stop using `--debug` :)

If so, do you have any hard requirements around the discussion from that thread? (e.g. the naming). Perhaps a `--defer-constraints` option? Given the way the Mutex is handled on parallelization, I think that approach might work...

(also, perhaps a way to specify that option by default, given a codebase with many FKs would _always_ want that option).

**Comment by ankane** [comment]
Hey @jmmastey, it'd be nice to better support foreign key constraints, but I feel like there may be a better way than the approach in #6, which requires a full schema sync. I'd like for someone to investigate alternative approaches (like possibly [disabling triggers](https://stackoverflow.com/questions/38112379/disable-postgresql-foreign-key-checks-for-migrations/38113838#38113838)) before merging that approach.

**Comment by jmmastey** [comment]
Thanks, I'll see if I can muck something together.

**Comment by ankane** [comment]
Another approach (and possibly the best) would be to resolve the dependency graph and sync the tables in that order (parallelizing where possible). [Condenser](https://github.com/TonicAI/condenser) takes this approach: https://www.tonic.ai/post/condenser-a-database-subsetting-tool/

**Comment by ankane** [comment]
Cleaning up stale issues. I think dependency resolution with Molinillo is the best place to start if someone wants to add this.

**Comment by ankane** [comment]
Just fyi, added a `--defer-constraints` option on master. It's a different approach than #6 (doesn't require a full schema sync) and still syncs one-at-a-time, but doesn't require you to specify the order of tables. There's also the option to disable triggers entirely, which can sync tables in parallel, but can silently break referential integrity. More info here: https://github.com/ankane/pgsync#foreign-keys

**Comment by jmmastey** [comment]
Thanks, I think that'll cover what I need. Appreciate you circling back.
