### ISSUE TITLE
Deadlock detected errors

### ISSUE THREAD

**Issue by ykostsik** [ankane/pgsync#60]
Hi @ankane,
I get the error when I'm dealing with data in the production database, that has lots of relations PK-FK between tables.  When pgsync runs in parallel  the tables with the similar list of dependencies, it causes the deadlock error like below.
```
# just show a list of dependencies for two tables
>pgsync tier
* Syncing tier
NOTICE:  truncate cascades to table "product"
NOTICE:  truncate cascades to table "rate"
NOTICE:  truncate cascades to table "offer"
NOTICE:  truncate cascades to table "action_impact"
NOTICE:  truncate cascades to table "uwm_data"

>pgsync state
* Syncing state
NOTICE:  truncate cascades to table "tp_insurance"
NOTICE:  truncate cascades to table "uwm_data"
NOTICE:  truncate cascades to table "c_score"
NOTICE:  truncate cascades to table "action_impact"
NOTICE:  truncate cascades to table "offer"
<...>
```
When we run `pgsync` or `pgsync group1`  the error is occurred.
```
2019-10-02 09:43:06.500 UTC [12571] ERROR:  deadlock detected
2019-10-02 09:43:06.500 UTC [12571] DETAIL:  Process 12571 waits for AccessExclusiveLock on relation 40292(action_impact) of database 39735; blocked by process 12569.
        Process 12569 waits for AccessExclusiveLock on relation 40843(uwm_data) of database 39735; blocked by process 12571.
        Process 12571: TRUNCATE "postgres"."state" CASCADE
        Process 12569: TRUNCATE "postgres"."tier" CASCADE
2019-10-02 09:43:06.500 UTC [12571] HINT:  See server log for query details.
2019-10-02 09:43:06.500 UTC [12571] STATEMENT:  TRUNCATE "postgres"."state" CASCADE
```
This is an extract from the entire list, in a real situation I have  4 or even more tables that are processed concurrently and have the similar list of related tables need to be truncated. 
All triggers on the target side are disabled.
I just use `--debug` as a workaround,  but it completely disables multitheading.

**Comment by ankane** [comment]
Hey @ykostsik, you'll need to use the `debug` option for now. See #59 for some ideas around foreign key improvements. Let's discuss it there if you have ideas.
