### ISSUE TITLE
Merging multiple DBs?

### ISSUE THREAD

**Issue by Fmstrat** [ankane/pgsync#61]
Can `pgsync` be used to merge multiple databases? So if I have these DBs all with the same schemas:

```
DB1 with tables that use UUIDs as keys with data for company 1
DB2 with tables that use UUIDs as keys with data for company 2
DB3 where I want all data for company 1 and 2 in
```

I'd like to merge DB1 and DB2 together into DB3.

**Comment by ankane** [comment]
Hey @Fmstrat, you should be able to do this with separate commands:

```sh
pgsync --from db1 --to db3 --preserve table1
pgsync --from db2 --to db3 --preserve table1
```

**Comment by Fmstrat** [comment]
Thanks. I will give that a shot.

**Comment by ankane** [comment]
Cleaning up issues
