### ISSUE TITLE
Parallel::UndumpableException: PG::NotNullViolation: ERROR:  null value in column "encrypted_password" violates not-null constraint

### ISSUE THREAD

**Issue by afuno** [ankane/pgsync#62]
Rails 5.2.3
Devise 4.7.1

---

I'm trying to synchronize a table with users between two different databases. Databases are different, but have the same scheme.

```
bundle exec pgsync --from db1 --to db2 --preserve users
bundle exec pgsync --from db2 --to db1 --preserve users
```

After executing the first command, I get this error:

```
bundler: failed to load command: pgsync (/Users/afuno/.rbenv/versions/2.6.2/bin/pgsync)
Parallel::UndumpableException: PG::NotNullViolation: ERROR:  null value in column "encrypted_password" violates not-null constraint
```

And:

```
DETAIL:  Failing row contains (705, user@email.com, 2019-08-20 18:11:51.115133, 2019-08-20 18:12:21.307266, null, null, 1, 2019-08-20 18:11:51.175513, 2019-08-20 18:11:51.175513, ::1, ::1, 3ge6662f06fe1e331e97421c0511892bfrqb1ec8, ST, L, null, null, f-7_2x.png, London, null, t, t, 2019-08-20 18:12:21.307266, 203140, null).
```

The fifth value in the list above is `encrypted_password`. For some reason, it is `null`. I checked the user `705` through the `rails console` - this field is not empty for him.

What to do?

**Comment by ankane** [comment]
Hey @afuno, the default `.pgsync.yml` has a data rule for `encrypted_*` columns that you'll need to update.

**Comment by afuno** [comment]
@ankane Thanks.
