### ISSUE TITLE
schema sync fails because of views

### ISSUE THREAD

**Issue by jensenak** [ankane/pgsync#66]
I'm working with a database that has several views. I typically run `--schema-only`, followed by a few commands to sync by group. However, on this particular database, some tables can't be dropped because they're in use by views. This means pgsync will fail to update the schema of those tables. In this case, with some tables modified and others not, it becomes difficult to get the database back to a correct state (rails migrations fail and manual work is required).

Is there a way to work around this within pgsync? Or should I plan to drop and recreate views before and after each sync?

**Comment by ankane** [comment]
Hey @jensenak, I'm not sure I follow the workflow. Can you give a minimal example that reproduces the issue (and any relevant errors/output)?

**Comment by jensenak** [comment]
Sure. We have a database we use for source data for testing. We have another database that devs can make modifications to. We want to periodically copy data back from the source to the dev database, overwriting changes that were made and resetting the schema. This allows us to refine our database update process by running repeated tests. I had hoped to automate this with pgsync.

However, both databases have views (mimicking production). These views prevent pgsync from overwriting the dev database schema (because it can't drop and recreate tables).

The simplest way to reproduce this is to create two tables and sync them to a second database. Then create a view on the second database that selects columns from both tables. Run pgsync again with the schema-first option (even without changes to the schema) and it will fail with messages like the following:

    pg_restore: dropping TABLE person
    pg_restore: [archiver (db)] Error from TOC entry 197; 1259 44161 TABLE person [my user]
    pg_restore: [archiver (db)] could not execute query: ERROR:  cannot drop table public.person because other objects depend on it
    DETAIL:  view public.example depends on table public.person
    HINT:  Use DROP ... CASCADE to drop the dependent objects too.
        Command was: DROP TABLE IF EXISTS public.person;

The process subsequently fails to create the tables because they exist, but that's expected.

If this isn't the intended use of pgsync, I'll find a different tool or write something in house. But if this is the intended use and I'm missing a simple flag or option, let me know.

**Comment by ankane** [comment]
Thanks @jensenak, makes sense. pgsync is primarily designed to sync data rather than schema changes (will make that more clear in the readme). My recommendation would be to manage schema changes with a migrations/schema change tool and then use pgsync to sync the actual data.

**Comment by jensenak** [comment]
That's fair. Thanks for the quick feedback. :)
