### ISSUE TITLE
Feature: flag to disable syncing of sequences

### ISSUE THREAD

**Issue by HarshaLaxman** [ankane/pgsync#68]

**Comment by ankane** [comment]
Hey @HarshaLaxman, this shouldn’t be too difficult. Can you explain the use case a bit more?

**Comment by HarshaLaxman** [comment]
Hi @ankane thanks for the quick response! We are syncing one way with writes in both regions. So data from A->B where B has writes that do not go to A. We are using separate offsets and incrementing by 100 to avoid overlap between regions.

**Comment by ankane** [comment]
Make sense, thanks @HarshaLaxman. Give master a shot with the `--no-sequences` option.

**Comment by HarshaLaxman** [comment]
Wow!!! Thanks so much that was quick :pray:
