### ISSUE TITLE
ID is blindly treated as convertible to an integer on random_phone use

### ISSUE THREAD

**Issue by xenji** [ankane/pgsync#72]
Hey!

First of all, thank you for creating this tool, it really solves a problem for me!

I've discovered an unwanted behavior where I suspect that the tool assumes `id` always being numeric. In my case, `id` is a `varchar` from a foreign system, identifying a person. I'm using the very cool PII-remover, but struggle with the tool's assumption, that the `id` is cast'able to a `bigint`.

I would expect the tool to not do any assumptions on the datatypes, but being convertible to a string (which I personally assume is reasonably safe to do).

I've attached as much information as I can disclose. Please get in touch if you need more in depth information or different than the one provided.

## Backtrace
```
Traceback (most recent call last):
	12: from /usr/local/bin/pgsync:23:in `<main>'
	11: from /usr/local/bin/pgsync:23:in `load'
	10: from /usr/local/share/gems/gems/pgsync-0.4.3/exe/pgsync:5:in `<top (required)>'
	 9: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/client.rb:24:in `perform'
	 8: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/client.rb:95:in `sync'
	 7: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/client.rb:272:in `in_parallel'
	 6: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/client.rb:272:in `each'
	 5: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/client.rb:96:in `block in sync'
	 4: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/table_sync.rb:138:in `sync'
	 3: from /usr/local/share/gems/gems/pg-1.2.2/lib/pg/connection.rb:166:in `copy_data'
	 2: from /usr/local/share/gems/gems/pgsync-0.4.3/lib/pgsync/table_sync.rb:139:in `block in sync'
	 1: from /usr/local/share/gems/gems/pg-1.2.2/lib/pg/connection.rb:194:in `copy_data'
/usr/local/share/gems/gems/pg-1.2.2/lib/pg/connection.rb:194:in `get_last_result': ERROR:  invalid input syntax for integer: "V00CWLR7" (PG::InvalidTextRepresentation)
```

## relevant config
```yaml
data_rules:
  kunde.telefonnummer: unique_phone
```

## relevant part of the generated statement:
```sql
"public"."kunde"."id"::text || '@example.org' AS "email", ("public"."kunde"."id"::bigint + 1000000000)::text AS "telefonnummer"
```

**Comment by ankane** [comment]
Hey @xenji, some of the data rules require the primary key to be numeric. Happy to accept a PR if there's a way to make it work with non-numeric ids.

**Comment by xenji** [comment]
Hey @ankane , thanks for letting me know. Due to time constraints, I could offer a small PR with a  README change to make this visible to the user. My workaround is using a random int and that works just fine for me.

**Comment by ankane** [comment]
Re note: good idea. Added on master.
