### ISSUE TITLE
--in-batches flag does not work with limits

### ISSUE THREAD

**Issue by mlarraz** [ankane/pgsync#76]
When I run
```
pgsync <mytable> "limit 1" --in-batches
```
I get
```
ERROR:  argument of AND must be type boolean, not type integer (PG::DatatypeMismatch)
```
Maybe the flag should be ignored if we can detect a limit in the query

**Comment by ankane** [comment]
Hey @mlarraz, thanks for the report. I'm not sure there's anything the library should do here. These options don't really make sense together, so an error seems fine.

**Comment by mlarraz** [comment]
The bigger problem I guess is really that `--in-batches` applies at the group level, so any queries inside of it that do something like this will stop working.

Ideally I could specify that some queries in a group should use batches but not others

**Comment by ankane** [comment]
Hey @mlarraz, sorry for the delay. `--in-batches` isn't designed to be used with groups. I'll likely add a warning in the next version and throw an error in 0.6.0.
