### ISSUE TITLE
no matches found: schema_name.*

### ISSUE THREAD

**Issue by ACPK** [ankane/pgsync#77]
As mentioned in https://github.com/ankane/pgsync/issues/22, I tried using `pgsync schema_name.* ` but I get the error below. I am also trying to sync a specific schema as a whole (i.e. not list each table).

    % pgsync blog.*
    zsh: no matches found: blog.*

**Comment by ankane** [comment]
Hey @ACPK, with ZSH, you need to quote arguments with special characters (like `*`).

```sh
pgsync "blog.*"
```
