### ISSUE TITLE
How to sync RDS databases present in 2 different VPCs

### ISSUE THREAD

**Issue by boddumanohar** [ankane/pgsync#78]
We have 2 postgres database that needs to be synced with each other. Both the databases are running inside 2 different VPCs. The database in each of the instance is accessible from the private subnet only. 

Our setup is this way: 
VPC1:
Bastion -> Ec2-in-Private-subnet -> DB

VPC2:
Bastion -> Ec2-in-private-subnet -> DB

is there way to get the both databases in sync with each other maybe using ansible or something?

**Comment by ankane** [comment]
Hi @boddumanohar, pgsync isn't design for two-way syncing. You'll need to find another tool.
