### ISSUE TITLE
Question: does pgsync support different schemas other than public?

### ISSUE THREAD

**Issue by WhatIfWeDigDeeper** [ankane/pgsync#80]
I saw this note in [0.3.1](https://www.rubydoc.info/gems/pgsync/0.3.1)

### TODO

Support for schemas other than `public`

Is this still a to do? Thanks

**Comment by ankane** [comment]
It syncs all schemas in your search path by default. You can also use `--all-schemas` or `--schemas schema1,schema2` or wildcards `pgsync "schema1.*"`.

**Comment by WhatIfWeDigDeeper** [comment]
Sorry for the ambiguous nature of my question. I meant when syncing data, DML. I don't need to sync the actual schema, DDL. However, using the `--schemas schema1` gets me closer so I thank you for pointing me to that.  However, it doesn't find the table when I do a subquery.

```yml
stores: "where id in (select store_id from products where id = {1})" 
```

`Table does not exist in source: {"stores"=>"where id in (select store_id from products where id = {1})"}`

If I prefix the table in the subquery,

```yml
stores: "where id in (select store_id from schema1.products where id = {1})" 
```

it gives a similar message.

``Table does not exist in source: {"stores"=>"where id in (select store_id from schema1.products where id = {1})"}`

If there is a solution to this, or if it's user error, it would be great if we could also do joins or queries:

```yml
stores: "join products on stores.id = products.store_id where products.id = {1})" 
```

This would assume that the select clause would only get the main table, `select * from stores`

Thanks for your help

**Comment by ankane** [comment]
The schema options don't change the search path, so you'll want to use:

```yml
schema1.stores: "where id in (select store_id from schema1.products where id = {1})" 
```
