### ISSUE TITLE
how to use pgsync.yml for rails env  database

### ISSUE THREAD

**Issue by wjiachao** [ankane/pgsync#82]
I want to use pgsync.yml  to config from  database and to database config.

But  not show database username and password, how to config use rails env ?

**Comment by ankane** [comment]
Hey @wjiachao, I'm not sure I understand the question. Can you give an example of what you're trying to do?

**Comment by ankane** [comment]
In general, pgsync's only integration with Rails is `pgsync --init` to see which tables to initially exclude).

**Comment by ankane** [comment]
Closing due to no response
