### ISSUE TITLE
Invalid connection string

### ISSUE THREAD

**Issue by ryankamalfa** [ankane/pgsync#83]
Hi,
I recieve error 
`Invalid connection string`
however my pgsync.yml is as below
`from: postgres://postgres:postgres@localhost:5432/postgres2
to_safe: true
to:postgres://username:password@database.postgres.database.azure.com:5432/postgres?ssl=true
`

Can you help ?

**Comment by ankane** [comment]
Hey @ryankamalfa, I don't see anything immediately from the above. I'd confirm each connection string works with `psql`.
