### ISSUE TITLE
Column name's display is shifting to the right

### ISSUE THREAD

**Issue by bdarcet** [ankane/pgsync#84]
Hi,

I've been using pgsync for a while now and I've noticed recently that there has been an update in the layout when you start a pgsync. But it seems like this layout is having some issues to display correctly. It could be because of the size of the line because the issue doesn't appear when the line to display is short.

Command :
`pgsync table_name "where column_name = XX" --no-rules --in-batches`

Result :
```
⠧ table_name where "id = XXXXX"
⠹ table_name where "id = XXXXXd" < XXXXXXXXX
⠹ table_name where "id = XXXXXd" < XXXXXXXXX
⠹ table_name where "id = XXXXXid" < XXXXXXXXX
```

It seems like the column_name, here "id" is moving to the right for some reason. The sync still works so it's only an issue with the display.

**Comment by ankane** [comment]
Hey @bdarcet, thanks for reporting! Fixed on master. Here are instructions if you want to try it: https://github.com/ankane/pgsync#upgrading

**Comment by bdarcet** [comment]
Hey @ankane, it seems to be working ! Thank you for your lightning fast fix ! 😄
