### ISSUE TITLE
Disable triggers when syncing data

### ISSUE THREAD

**Issue by bartjuh4** [ankane/pgsync#85]
For my project i'm trying to use this awesome tool, but ran into some problems. The problem with foreign keys we managed to resolve but our database has some triggers that are giving some headache.

We need an option to disable the database table triggers or ignore duplicate errors. I managed to make some changes to the core of this tool to test if my idea would work but don't know how to integrate this nicely in this package.

I changed the insert query a bit and appended the following: `ON CONFLICT ON CONSTRAINT some_constraint DO NOTHING`

I need to make the 'some_constraint' dynamic and configurable somehow.

**Comment by ankane** [comment]
Hey @guilhermeyo, added an experimental `--disable-user-triggers` option on master.

There are also a few more options for foreign keys (since you mentioned it): https://github.com/ankane/pgsync#foreign-keys

You can try it out with:

```sh
gem install specific_install
gem specific_install https://github.com/ankane/pgsync.git
```

Let me know how it goes.

**Comment by bartjuh4** [comment]
Nice, just tested it out and does exactly what we need for our project. Thanks!

**Comment by ankane** [comment]
Great to hear, thanks for confirming!
