### ISSUE TITLE
invalid percent-encoded token: "eeieiw%jdjd%"

### ISSUE THREAD

**Issue by cuphan** [ankane/pgsync#86]
Hi there

I have this error when run pgsync tbl_mobile
my password has % Do you know how to set the variable inside .pgsync.yml 

for example:

password: 'eeieiw%jdjd%'
from: postgres://abc:{{password}}@192.168.1.23:5432/abc
to: postgres://def:{{password}}@localhost:5432/abc

**Comment by ankane** [comment]
Hey @cuphan, be sure to percent-encode passwords like with `psql`. A quick search of that error message should show you how.
