### ISSUE TITLE
Bidirectional relationships sync

### ISSUE THREAD

**Issue by orangeStas** [ankane/pgsync#87]
Is it possible to handle sync of 2 tables where 1st table has a FK on a second table and vise versa?

I'm trying to sync 2 tables using groups feature with `--debug` flag but it fails on constraint violation.
One of possible solution could be using transaction while sync or extra parameter like `--ignore-colums` to exclude table column from sync.

**Comment by ankane** [comment]
Hey @orangeStas, added a few experimental options for foreign keys on master: https://github.com/ankane/pgsync#foreign-keys

You can try it out with:

```sh
gem install specific_install
gem specific_install https://github.com/ankane/pgsync.git
```

Let me know if that helps.

**Comment by orangeStas** [comment]
Hi @ankane, `--defer-constraints` feature is awesome, solved my problem.

Thanks a lot!

**Comment by ankane** [comment]
Great, thanks for confirming!
