### ISSUE TITLE
undefined method `conninfo_hash'

### ISSUE THREAD

**Issue by jdheyburn** [ankane/pgsync#88]
Hello

I am doing a feasibility test for whether pgsync can help us with a Postgres migration.

I am running on CentOS with the below versions.

```
$ gem list pg

*** LOCAL GEMS ***

pg (1.2.3)
pgsync (0.5.4)
```

The error I receive is this. I'm not familiar with ruby so I'm unsure if this is something on my side or on the app. I've completed my `.pgsync.yml` to just have the `from` and `to` fields completed.

```
$ pgsync --list
Traceback (most recent call last):
        7: from /usr/local/bin/pgsync:23:in `<main>'
        6: from /usr/local/bin/pgsync:23:in `load'
        5: from /usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/exe/pgsync:7:in `<top (required)>'
        4: from /usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/lib/pgsync/client.rb:32:in `start'
        3: from /usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/lib/pgsync/client.rb:24:in `perform'
        2: from /usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/lib/pgsync/sync.rb:33:in `perform'
        1: from /usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/lib/pgsync/data_source.rb:19:in `host'
/usr/local/lib/ruby/gems/2.5.0/gems/pgsync-0.5.4/lib/pgsync/data_source.rb:148:in `conninfo': undefined method `conninfo_hash' for #<PG::Connection:0x0000000001c8c250> (NoMethodError)
```

I am able to connect to the DBs using the connection string provided in the .yml files.

**Comment by ankane** [comment]
Hey @jdheyburn, can you share the version of CentOS and Postgres you're on, as well as the output of `psql --version`?

**Comment by jdheyburn** [comment]
I tried on two diff `psql` versions, originally it was pointing to `psql (PostgreSQL) 9.2.24` - after pointing to `psql (PostgreSQL) 10.10` I got the same error.

CentOS version:
```
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
```

**Comment by ankane** [comment]
The error seems to indicate the `pg` gem was compiled against Postgres 9.2 or less. https://github.com/ged/ruby-pg/blob/v1.2.3/lib/pg/connection.rb#L240

Try installing the `pg` gem again and setting `--with-pg-config` if needed:

```sh
gem install pg -- --with-pg-config=/path/to/pg_config
```

**Comment by jdheyburn** [comment]
Thanks - I've got it working now. I've removed the old postgres lib and rebuilt on the new one.

Thanks for the quick resolution on this! 👍

**Comment by ankane** [comment]
Great, glad it's working. I've added a more friendly error message on master.
