### ISSUE TITLE
Setup using Google cloud run

### ISSUE THREAD

**Issue by griseau** [ankane/pgsync#89]
Hello, 

I'm trying to use it on Google cloud run. For this, the hostname of the database is something like : /cloudsql/project:location:instance (according to Google cloud documentation, https://cloud.google.com/sql/docs/postgres/connect-run#connecting_to). So in the .pgsync.yml I have something like 

`from : postgres://USER:PASSWORD@/cloudsql/PROJECT:LOCATION:INSTANCE/DATABASE`

But it does not work ... Maybe the parsing of the url is not correct ? 

Thanks for your help !

**Comment by ankane** [comment]
Hey @griseau, I'd first get it working with `psql`, then copy it over to `pgsync`. Be sure to percent-encode the path in the hostname.

```psql
psql postgres://%2Fcloudsql%2FINSTANCE_CONNECTION_NAME/testdb
```

https://www.postgresql.org/docs/current/libpq-connect.html

**Comment by griseau** [comment]
I was missing the percent-encoding ! Thanks a lot
