### ISSUE TITLE
RDS ERROR: permission denied: "RI_ConstraintTrigger" is a system trigger

### ISSUE THREAD

**Issue by mcg** [ankane/pgsync#94]
Trying to use this against an RDS database with the `--disable-integrity` option. It is failing with:

`ERROR: permission denied: "RI_ConstraintTrigger...." is a system trigger`

There appears to be an alternative way to disable triggers on RDS with `set session_replication_role = replica;`

**Comment by ankane** [comment]
Hey @mcg, thanks for the info. Can you confirm the alternative method works on your RDS instance? From the Postgres docs, both disabling triggers and setting `session_replication_role` require superuser privileges, but it's possible RDS allows one and not the other.

Ref: https://www.postgresql.org/docs/current/runtime-config-client.html

**Comment by mcg** [comment]
It appears to be granted to the `rds_superuser` role. I added a `set session_replication_role = replica;` into my copy of `pgsync` and was able to run a sync successfully. I guess it's worth looking at adding properly.

**Comment by ankane** [comment]
Great, added `--disable-integrity-v2` on master. Let me know if that does it.

https://github.com/ankane/pgsync#upgrading

**Comment by mcg** [comment]
That change appears to work for us. Since it requires `rds_superuser` it might be best as an additional option, rather than replacing the existing `--disable-integrity`. Huge thanks for getting that out so fast.

**Comment by ankane** [comment]
Just pushed a new release. `--disable-integrity` now uses the new method if it detects you're on Amazon RDS. Thanks for the info and testing!

**Comment by ankane** [comment]
I just added a `--defer-constraints-v2` option as well, which temporarily defers all constraints, even those marked as `NOT DEFERRABLE` (the default). If you have a chance to try it, let me know how it goes. This should be much safer than disabling integrity.

**Comment by ankane** [comment]
Also added SQL commands to the `--debug` output on master if that helps.

**Comment by mcg** [comment]
The new debugging output is helpful. Our issue is with a 4Gig table that is causing "statement timeouts" after hitting our 2 hour limit. This seems extremely long for just a 4G table. I cannot see any obvious reasons why this is taking so long. Neither DB's are being used. No lock contention. Bumping up timeouts to see if it will actually complete.

**Comment by mcg** [comment]
Let it run for 6 hours before stopping the sync.

**Comment by ankane** [comment]
Hmm, not sure what the issue would be. Does it work with other tables?

**Comment by mcg** [comment]
Yeah, it works with other tables, but this is the largest we are attempting to sync. We are excluding others. It doesn't have an issue with some ~2G tables we have.

**Comment by ankane** [comment]
Curious to see if others run into the same issue. One other thing you could try is setting a short lock timeout on both the source and destination users to confirm there's no locking.

```sql
ALTER ROLE myuser SET lock_timeout = '5s';
```
