### ISSUE TITLE
Skip data sync for 1 large table

### ISSUE THREAD

**Issue by kbaum** [ankane/pgsync#95]
We have 1 large table that we need the schema for but would like to skip the data. Is there a way to exclude a table just for the data but not the schema? I have been getting this done by executing two separate pgsync commands.. 1 for the schema and one just for the data. Thx.

**Comment by ankane** [comment]
Hey @kbaum, there's not a way to do this in one command (and think it's probably not common enough to add).

**Comment by kbaum** [comment]
Ok makes sense. Thanks!
