### ISSUE TITLE
Sync with foreign keys

### ISSUE THREAD

**Issue by griseau** [ankane/pgsync#96]
Hello, 

I'm trying to sync some tables with foreign keys. Let's say I have 2 tables table1, table2.
Table1 has a primary key `id` that is referenced as foreign key in table2.

I want to sync only Table1. How to deal with rows deleted from table1 ? If using --truncate it also removes all the rows from table 2 ... 

Let me know if it's unclear, 
Thanks for your help

**Comment by ankane** [comment]
Hey @griseau, pgsync doesn't have the ability to do that.

**Comment by griseau** [comment]
Would something like this do the job : 

`pgsync table2 "where id_table1 not in (select id from table1)" --truncate` 
to first remove rows in table2, and then` pgsync table1` 

Thanks !

**Comment by ankane** [comment]
Hey @griseau, that's something you should be able to try on your own.
