### ISSUE TITLE
Preservative schema sync

### ISSUE THREAD

**Issue by gregdan3** [ankane/pgsync#98]
If I have a table `public.foo` in database `a`, and a nearly identical table `public.foo` in database `b`, where the only difference between them is that `b.public.foo` is missing an index or a column (for example), the only means pgsync provides (as far as I am aware) to synchronize them is to either overwrite the data in `b.public.foo` with that in `a.public.foo` or to truncate `b.public.foo` and leave only the structure of the schema. 

Is it possible to synchronize these two separate tables' schemas without destructing the contained data in the target table?

**Comment by ankane** [comment]
Hey @gregdan3, the schema sync is very basic (as pgsync's main focus is data), so this isn't possible.

**Comment by gregdan3** [comment]
Gotcha. Thanks for the help; I'll close.
