### ISSUE TITLE
Missing rows in destination table

### ISSUE THREAD

**Issue by itmecho** [ankane/pgsync#99]
We're using `pgsync` to synchronise data between our platform and reporting database and for some reason it's not copying all rows from one of the tables. We're using `where 1 = 1` to sync all the records. I manually truncated the table and ran the sync task again and it worked properly but this morning I checked again and there are missing records. I thought I could use the truncate option but I don't think I can specify individual tables in the config file like I can with exclude. I don't want to truncate all the tables as some of them have a lot of rows that would put a lot of load on both databases to copy every time. 

Is granular control of tables to truncate a feature that could be added?

**Comment by ankane** [comment]
Hey @itmecho, are you able to separate it into two commands: one with tables to truncate and the rest without it?

**Comment by pavliczgabor** [comment]
We are looking for a solution for the same purpose (sync data to reporting database) as itmecho, and pgsync is an option.
Missing records are quite a big problem in this situation. 

Is this issue caused by a bug or some configuration problem?

**Comment by ankane** [comment]
@pavliczgabor I haven't seen any evidence of missing rows, but feel free to follow up if it's something you encounter.

**Comment by ankane** [comment]
Cleaning up stale issues
